import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4'
const SUPABASE_URL='https://nqcshihyfhthywpseilx.supabase.co',SUPABASE_KEY='sb_publishable_lD--sdVpwV9djLF28XW1Jg_95DPa58G'
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:'pkce'}})
const $=s=>document.querySelector(s)
function message(v,danger=false){$('#message').textContent=v;$('#message').classList.toggle('danger',danger)}
async function sha1Hex(value){const d=await crypto.subtle.digest('SHA-1',new TextEncoder().encode(value));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('').toUpperCase()}
async function safePassword(password){if(password.length<12)throw new Error('Use at least 12 characters.');const h=await sha1Hex(password),prefix=h.slice(0,5),suffix=h.slice(5);const res=await fetch(`https://api.pwnedpasswords.com/range/${prefix}`,{headers:{'Add-Padding':'true'}});if(!res.ok)throw new Error('The breached-password check is unavailable. Try again before setting the password.');const body=await res.text();for(const row of body.split(/\r?\n/)){const [candidate,count]=row.trim().split(':');if(candidate===suffix&&Number(count||0)>0)throw new Error('That password appears in known breach data. Choose another password.')}return true}
async function verifyRaw(raw){const value=String(raw||'').trim();if(!value)throw new Error('Paste the complete link from the F.S.A. email.');let u;try{u=new URL(value)}catch{throw new Error('That is not a valid URL.')}if(u.origin!==SUPABASE_URL)throw new Error('That link was not issued by the F.S.A. Supabase project.');const type=u.searchParams.get('type');if(!['invite','recovery','magiclink','email'].includes(type||''))throw new Error('That link is not an account invitation or recovery link.');const tokenHash=u.searchParams.get('token_hash')||u.searchParams.get('token');if(!tokenHash)throw new Error('The link has no one-time token.');const {data,error}=await supabase.auth.verifyOtp({token_hash:tokenHash,type});if(error)throw error;if(!data?.session)throw new Error('The one-time token did not create a session.');history.replaceState({},document.title,location.pathname);$('#linkStep').classList.add('hidden');$('#passwordStep').classList.remove('hidden');message('Link verified. Choose your F.S.A. password.')}
$('#verifyLink').addEventListener('click',async()=>{const b=$('#verifyLink');b.disabled=true;try{await verifyRaw($('#authLink').value)}catch(e){message(e.message||String(e),true)}finally{b.disabled=false}})
$('#savePassword').addEventListener('click',async()=>{const b=$('#savePassword'),p=$('#password').value,c=$('#confirm').value;if(p!==c)return message('Passwords do not match.',true);b.disabled=true;try{message('Checking password security…');await safePassword(p);const {error}=await supabase.auth.updateUser({password:p});if(error)throw error;message('Account activated. Opening F.S.A.…');location.replace('./?account=activated')}catch(e){message(e.message||String(e),true);b.disabled=false}})
(async()=>{const q=new URLSearchParams(location.search),type=q.get('type'),token=q.get('token_hash');if(type&&token){try{await verifyRaw(`${SUPABASE_URL}/auth/v1/verify?type=${encodeURIComponent(type)}&token_hash=${encodeURIComponent(token)}`)}catch(e){message(e.message||String(e),true)}}})()
