(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const storeKey='fsa.arcade.v3';
let profile={credits:12450,level:12,xp:0};
try{profile={...profile,...JSON.parse(localStorage.getItem(storeKey)||'{}')}}catch{}
const save=()=>{localStorage.setItem(storeKey,JSON.stringify(profile));renderWallet()};
function renderWallet(){['wallet','fgCredits','slotWallet'].forEach(id=>{const el=document.getElementById(id);if(el)el.textContent=Math.floor(profile.credits).toLocaleString()});const lv=$('#level');if(lv)lv.textContent=profile.level}
renderWallet();
const fishGames=[
{name:'Reef Run',icon:'🦈',theme:['#003d63','#190d3c'],glow:'#1be6ff',tag:'CLASSIC',desc:'Balanced schools, treasure bursts and Kraken boss.',spawn:1.25,hp:1,reward:1,speed:1,boss:'Kraken',bossIcon:'🐙',special:'Treasure Surge'},
{name:'Dragon Depths',icon:'🐉',theme:['#340b08','#0b203a'],glow:'#ff501d',tag:'BOSS HUNT',desc:'Heavy targets and dramatic boss waves.',spawn:.9,hp:1.5,reward:1.6,speed:.9,boss:'Abyss Dragon',bossIcon:'🐲',special:'Inferno Chain'},
{name:"Pirate's Plunder",icon:'🏴‍☠️',theme:['#112332','#40220b'],glow:'#ffcc51',tag:'TREASURE',desc:'Dense schools, loot targets and chain events.',spawn:1.45,hp:.9,reward:1.15,speed:1.1,boss:'Dread Captain',bossIcon:'💀',special:'Gold Rush'},
{name:'Atlantis Rising',icon:'🔱',theme:['#073c47','#152557'],glow:'#36ffe7',tag:'WAVE',desc:'Formation waves and guardian feature rounds.',spawn:1.2,hp:1.15,reward:1.25,speed:.95,boss:'Atlas Guardian',bossIcon:'🗿',special:'Trident Pulse'},
{name:'Ice Tide',icon:'❄️',theme:['#0c4d78','#09162f'],glow:'#8aeaff',tag:'FREEZE',desc:'Fast schools and freeze windows.',spawn:1.55,hp:.85,reward:1.05,speed:1.35,boss:'Frost Leviathan',bossIcon:'🐋',special:'Deep Freeze'},
{name:'Lava Reef',icon:'🌋',theme:['#5f1405','#1c0705'],glow:'#ff6a18',tag:'HEAT',desc:'Durable creatures and escalating feature rounds.',spawn:1,hp:1.35,reward:1.5,speed:1,boss:'Magma Maw',bossIcon:'🐲',special:'Heat Wave'},
{name:'Storm Seas',icon:'⚡',theme:['#10194b','#06394b'],glow:'#9ea7ff',tag:'CHAIN',desc:'Lightning fish and chain-hit opportunities.',spawn:1.5,hp:.9,reward:1.2,speed:1.25,boss:'Tempest Ray',bossIcon:'🦅',special:'Lightning Chain'},
{name:'Jade Dragon',icon:'🐲',theme:['#054a36','#08271d'],glow:'#7cff94',tag:'PRECISION',desc:'Premium targets with tighter windows.',spawn:.95,hp:1.1,reward:1.65,speed:1.1,boss:'Jade Emperor',bossIcon:'🐉',special:'Emerald Focus'},
{name:'Neon Ocean',icon:'🪼',theme:['#171052','#3e0c55'],glow:'#ff4bea',tag:'COMBO',desc:'Very dense schools and rapid-fire scoring.',spawn:1.8,hp:.75,reward:.9,speed:1.2,boss:'Pulse Jelly',bossIcon:'🪼',special:'Neon Frenzy'},
{name:'Ancient Ruins',icon:'🏛️',theme:['#2d2c15','#073543'],glow:'#e6d06e',tag:'RELICS',desc:'Relic fish and power-up feature targets.',spawn:1.15,hp:1.1,reward:1.2,speed:.9,boss:'Stone Colossus',bossIcon:'🗿',special:'Relic Wake'},
{name:'Mecha Marine',icon:'🤖',theme:['#182b36','#11161e'],glow:'#44d7ff',tag:'ARMOR',desc:'Armored targets and EMP effect fish.',spawn:1.05,hp:1.45,reward:1.4,speed:1.05,boss:'Titan Sub',bossIcon:'🤖',special:'EMP Burst'},
{name:'Coral Chaos',icon:'🐡',theme:['#5b164f','#0a3956'],glow:'#ff8fe7',tag:'PARTY',desc:'Crowded, fast, colorful bonus schools.',spawn:1.95,hp:.7,reward:.85,speed:1.4,boss:'Mega Puffer',bossIcon:'🐡',special:'School Frenzy'},
{name:"Kraken's Lair",icon:'🐙',theme:['#250e35','#031f35'],glow:'#af62ff',tag:'SURVIVAL',desc:'Long boss phases with tentacle adds.',spawn:.85,hp:1.8,reward:2,speed:.85,boss:'Prime Kraken',bossIcon:'🐙',special:'Tentacle Storm'},
{name:'Treasure Trials',icon:'💰',theme:['#513309','#0b2838'],glow:'#ffd15c',tag:'OBJECTIVE',desc:'Timed treasure targets and bonus waves.',spawn:1.3,hp:1,reward:1.3,speed:1,boss:'Vault Keeper',bossIcon:'🦀',special:'Treasure Surge'},
{name:'Boss Rush',icon:'👹',theme:['#450606','#170e20'],glow:'#ff354d',tag:'ENDGAME',desc:'Continuous mini-boss gauntlet.',spawn:.75,hp:1.65,reward:1.9,speed:1.1,boss:'Abyss King',bossIcon:'👹',special:'Overdrive'}];
const rooms=[{name:'Bronze Reef',min:1,max:10,ai:2,pace:.9,label:'CASUAL'},{name:'Silver Current',min:5,max:50,ai:3,pace:1.05,label:'STANDARD'},{name:'Gold Abyss',min:10,max:100,ai:3,pace:1.2,label:'HIGH ACTION'}];
const slots=[['Ocean Fortune','🐬'],['Treasure Reels','💰'],["Siren's Gold",'🧜‍♀️'],['Legend of Atlantis','🔱'],['Shark Jackpot','🦈'],['Pearl Rush','🦪'],['Kraken Spins','🐙'],['Reef Riches','🐠'],['Lucky Tide','7️⃣'],['Deep Diamonds','💎'],['Golden Anchor','⚓'],["Mermaid's Treasure",'🧜‍♀️'],['Pirate Jackpot','🏴‍☠️'],['Coral Cash','🪸'],["Neptune's Wheel",'🎡'],['Sea King 777','👑'],['Ocean Wilds','🌊'],['Diamond Dolphin','🐬'],['Wild Pearls','🦪'],['Treasure Temple','🏛️']].map((x,i)=>({name:x[0],icon:x[1],hue:(i*31)%360}));
$('#fishCards').innerHTML=fishGames.map((g,i)=>`<article class="gameCard" onclick="openRoomSelect(${i})"><div class="tag">${g.tag}</div><div class="art" data-icon="${g.icon}" style="--c1:${g.theme[0]};--c2:${g.theme[1]};--glow:${g.glow}88"></div><div class="cardBody"><b>${i+1}. ${g.name}</b><small>${g.desc}</small></div></article>`).join('');
$('#slotCards').innerHTML=slots.map((g,i)=>`<article class="slotCard" onclick="openSlot(${i})"><div class="tag">SLOT</div><div class="art" data-icon="${g.icon}" style="--c1:hsl(${g.hue} 58% 20%);--c2:hsl(${(g.hue+70)%360} 58% 10%);--glow:hsl(${g.hue} 90% 60%)"></div><div class="cardBody"><b>${g.name}</b><small>Original virtual-credit reel game</small></div></article>`).join('');
$$('[data-scroll]').forEach(b=>b.addEventListener('click',()=>document.getElementById(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'})));
window.closeModal=id=>$('#'+id)?.classList.remove('on');
let selectedGame=0,selectedRoom=1;
window.openRoomSelect=i=>{selectedGame=i;const g=fishGames[i];$('#roomTitle').textContent=g.name+' · Choose Table';$('#roomCards').innerHTML=rooms.map((r,ri)=>`<button class="roomCard" onclick="openFish(${i},${ri})"><b>${r.name}</b><span>${r.label}</span><small>Shot ${r.min}–${r.max} · ${r.ai} simulated seats · ${Math.round(r.pace*100)}% pace</small></button>`).join('');$('#roomModal').classList.add('on')};
let g=fishGames[0],room=rooms[1],session=null,fish=[],shotsFx=[],particles=[],last=0,spawnClock=0,formationClock=0,aiClock=0,anim=0,auto=false,lock=false,lockedId=null,telemetry=[],freezeUntil=0,bannerUntil=0,bannerText='';
const cv=$('#arena'),ctx=cv.getContext('2d');
const types=[{name:'Minnow',icon:'🐟',mult:2,hp:2,r:22,effect:null},{name:'Butterfly',icon:'🐠',mult:4,hp:4,r:26,effect:null},{name:'Puffer',icon:'🐡',mult:8,hp:8,r:30,effect:'bomb'},{name:'Turtle',icon:'🐢',mult:12,hp:11,r:36,effect:null},{name:'Ray',icon:'🟦',mult:18,hp:15,r:42,effect:'lightning'},{name:'Shark',icon:'🦈',mult:35,hp:26,r:52,effect:null},{name:'Golden Fish',icon:'🐟',mult:60,hp:34,r:46,effect:'gold'},{name:'Freeze Crab',icon:'🦀',mult:20,hp:16,r:40,effect:'freeze'},{name:'Net Fish',icon:'🐙',mult:28,hp:20,r:44,effect:'net'}];
function emit(type,data={}){telemetry.push({schema:'fsa.telemetry.v3',id:crypto.randomUUID(),time:new Date().toISOString(),game:g.name,room:room.name,sessionId:session?.id||null,type,source:'FSA-exact-owned',...data});telemetry=telemetry.slice(-8000)}
window.openFish=(i,ri=1)=>{selectedGame=i;selectedRoom=ri;g=fishGames[i];room=rooms[ri];closeModal('roomModal');$('#fishTitle').textContent=g.name+' · '+room.name;$('#fishSub').textContent=`${g.desc} · ${room.ai+1}-seat table simulation`;$('#rules').innerHTML=`<p><b>${g.special}</b></p><p>Room shot range: ${room.min}–${room.max}</p><p>Target values are shown as multipliers. Larger and special targets take more fire.</p><p>Simulated seats compete for finishing shots; boss credit goes to the seat landing the final hit.</p>`;$('#fishModal').classList.add('on');startFishSession();buildCannons();cancelAnimationFrame(anim);last=performance.now();anim=requestAnimationFrame(loop)};
function buildCannons(){const vals=[];for(let v=room.min;v<=room.max;v+=room.max<=10?1:room.max<=50?5:10)vals.push(v);const idx=Math.max(0,Math.floor(vals.length/3));session.cannon=vals[idx]||room.min;$('#cannonTray').innerHTML=`<button class="btn" id="cannonDown">−</button><div class="cannonCore">⚡ <b id="cannonValue">${session.cannon}</b><small>shot</small></div><button class="btn" id="cannonUp">+</button><button class="btn" id="lockBtn">LOCK</button><button class="btn" id="autoBtn">AUTO</button>`;const set=n=>{session.cannon=vals[Math.max(0,Math.min(vals.length-1,n))];$('#cannonValue').textContent=session.cannon;emit('cannon_changed',{value:session.cannon})};let vi=vals.indexOf(session.cannon);$('#cannonDown').onclick=()=>{vi--;set(vi);vi=vals.indexOf(session.cannon)};$('#cannonUp').onclick=()=>{vi++;set(vi);vi=vals.indexOf(session.cannon)};$('#lockBtn').onclick=toggleLock;$('#autoBtn').onclick=toggleAuto}
window.startFishSession=()=>{session={id:crypto.randomUUID(),score:0,shots:0,hits:0,kills:0,cannon:room.min,bossProgress:0,boss:null,started:Date.now(),seatScores:[0,0,0,0]};fish=[];shotsFx=[];particles=[];auto=false;lock=false;lockedId=null;freezeUntil=0;emit('session_start',{game:g.name,room:room.name});renderFishHud();spawnFormation()};
function spawnFormation(){if(!session)return;const count=7+Math.floor(Math.random()*8),y0=100+Math.random()*300,dir=Math.random()<.5?-1:1;for(let i=0;i<count;i++){setTimeout(()=>makeFish(false,{y:y0+Math.sin(i*.8)*60,dir}),i*70)}banner('SCHOOL INCOMING',900)}
function makeFish(boss=false,opt={}){if(!session)return;if(boss){const hp=420*g.hp*room.pace;const f={id:crypto.randomUUID(),name:g.boss,icon:g.bossIcon,x:cv.width+120,y:220,vx:-36*g.speed,hp,maxHp:hp,r:90,mult:120,boss:true,effect:'boss',owner:null};fish.push(f);session.boss=f;banner('BOSS ENTERS · '+g.boss,1700);emit('boss_spawned',{targetId:f.id,hp,multiplier:f.mult});return}const t=types[(Math.random()*types.length)|0],dir=opt.dir??(Math.random()<.82?-1:1),hp=t.hp*g.hp*(.75+Math.random()*.55);const f={id:crypto.randomUUID(),name:t.name,icon:t.icon,x:dir<0?cv.width+70:-70,y:opt.y??(80+Math.random()*(cv.height-220)),vx:dir*(55+Math.random()*95)*g.speed,hp,maxHp:hp,r:t.r,mult:Math.max(1,Math.round(t.mult*g.reward)),boss:false,effect:t.effect,owner:null,wobble:Math.random()*6.28};fish.push(f);emit('target_spawned',{targetId:f.id,species:f.name,trueHp:f.hp,multiplier:f.mult,effect:f.effect})}
function targetAt(x,y){let hit=null,bd=1e9;for(const f of fish){const d=Math.hypot(f.x-x,f.y-y);if(d<f.r+14&&d<bd){bd=d;hit=f}}return hit}
function applyEffect(f,seat){if(!f.effect)return;if(f.effect==='freeze'){freezeUntil=performance.now()+4500;banner('DEEP FREEZE!',1300)}else if(f.effect==='lightning'){fish.filter(z=>z!==f).sort(()=>Math.random()-.5).slice(0,5).forEach(z=>damageTarget(z,session.cannon*1.6,seat,true));banner('LIGHTNING CHAIN!',1100)}else if(f.effect==='bomb'){fish.filter(z=>Math.hypot(z.x-f.x,z.y-f.y)<220).forEach(z=>damageTarget(z,session.cannon*2.2,seat,true));banner('BOMB BLAST!',900)}else if(f.effect==='net'){fish.filter(z=>Math.hypot(z.x-f.x,z.y-f.y)<170).forEach(z=>damageTarget(z,session.cannon*1.4,seat,true));banner('NET CAPTURE!',900)}else if(f.effect==='gold'){profile.credits+=Math.round(f.mult*session.cannon*.5);banner('GOLD RUSH!',1000)}}
function damageTarget(f,dmg,seat=0,fromEffect=false){if(!f||f.hp<=0)return;f.hp-=dmg;f.owner=seat;particles.push({x:f.x,y:f.y,t:0,c:seat});emit('target_hit',{targetId:f.id,seat,damage:dmg,trueHpAfter:Math.max(0,f.hp),effect:fromEffect});if(f.hp<=0){const award=Math.round(f.mult*(seat===0?session.cannon:Math.max(room.min,session.cannon*.7)));session.seatScores[seat]+=award;if(seat===0){session.kills++;session.score+=award;profile.credits+=award;profile.xp+=award;profile.level=Math.max(profile.level,1+Math.floor(profile.xp/900));applyEffect(f,seat)}emit('target_destroyed',{targetId:f.id,seat,multiplier:f.mult,award,boss:f.boss});if(f.boss){session.boss=null;session.bossProgress=0;banner((seat===0?'YOU':'SEAT '+(seat+1))+' LANDED THE BOSS!',1800)}else session.bossProgress+=5+Math.random()*8;fish=fish.filter(z=>z!==f)}}
function fireAt(x,y,seat=0){if(!session)return;const shot=seat===0?session.cannon:Math.max(room.min,Math.round(session.cannon*(.5+Math.random())));if(seat===0){if(profile.credits<shot)return;profile.credits-=shot;session.shots++}shotsFx.push({x1:seat===0?cv.width/2:[70,cv.width-70,70][seat-1]||70,y1:seat===0?cv.height-24:[70,70,cv.height-70][seat-1]||70,x2:x,y2:y,t:0,seat});emit('shot_fired',{seat,x,y,cost:shot});const hit=targetAt(x,y);if(hit){if(seat===0)session.hits++;damageTarget(hit,shot*(.75+Math.random()*.45),seat)}if(seat===0){save();renderFishHud()}}
function pointerToArena(e){const r=cv.getBoundingClientRect();return{x:(e.clientX-r.left)*cv.width/r.width,y:(e.clientY-r.top)*cv.height/r.height}}
let holdTimer=null;cv.addEventListener('pointerdown',e=>{const p=pointerToArena(e);if(lock){const h=targetAt(p.x,p.y);if(h)lockedId=h.id}fireAt(p.x,p.y,0);clearInterval(holdTimer);holdTimer=setInterval(()=>{const t=lock&&lockedId?fish.find(z=>z.id===lockedId):null;fireAt(t?.x??p.x,t?.y??p.y,0)},145)});['pointerup','pointercancel','pointerleave'].forEach(ev=>cv.addEventListener(ev,()=>clearInterval(holdTimer)));
window.toggleAuto=()=>{auto=!auto;$('#autoBtn')?.classList.toggle('primary',auto);emit('auto_fire',{enabled:auto})};window.toggleLock=()=>{lock=!lock;lockedId=null;$('#lockBtn')?.classList.toggle('primary',lock);emit('lock_on',{enabled:lock})};window.exportTelemetry=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(telemetry,null,2)],{type:'application/json'}));a.download='fsa-telemetry-v3.json';a.click();URL.revokeObjectURL(a.href)};
function renderFishHud(){if(!session)return;$('#fgCredits').textContent=Math.floor(profile.credits).toLocaleString();$('#fgScore').textContent=session.score;$('#shots').textContent=session.shots;$('#kills').textContent=session.kills;$('#acc').textContent=session.shots?Math.round(session.hits/session.shots*100)+'%':'0%';$('#fgBoss').textContent=session.boss?session.boss.name:'—';$('#bossMeter').style.width=Math.min(100,session.bossProgress)+'%';const seats=$('#seatHud');if(seats)seats.innerHTML=session.seatScores.map((s,i)=>`<span class="seat ${i===0?'you':''}">P${i+1} <b>${Math.round(s)}</b></span>`).join('')}
function banner(text,ms=1000){bannerText=text;bannerUntil=performance.now()+ms}
function drawTarget(f,t){ctx.save();ctx.translate(f.x,f.y+Math.sin(t*.003+f.wobble)*8);if(f.vx>0)ctx.scale(-1,1);ctx.shadowBlur=f.boss?28:12;ctx.shadowColor=f.boss?'#ffd059':g.glow;ctx.font=(f.boss?98:Math.max(40,f.r*1.55))+'px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(f.icon,0,0);ctx.scale(f.vx>0?-1:1,1);ctx.shadowBlur=10;ctx.fillStyle='#08131ddd';ctx.strokeStyle='#ffd76c';ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(-30,f.r+9,60,24,8);ctx.fill();ctx.stroke();ctx.fillStyle='#fff2a7';ctx.font='bold 15px system-ui';ctx.fillText('×'+f.mult,0,f.r+21);if(f.boss){ctx.fillStyle='#000c';ctx.fillRect(-90,-f.r-28,180,10);ctx.fillStyle='#ffb23c';ctx.fillRect(-90,-f.r-28,180*Math.max(0,f.hp/f.maxHp),10)}if(lock&&lockedId===f.id){ctx.strokeStyle='#ffdf58';ctx.lineWidth=3;ctx.setLineDash([10,6]);ctx.beginPath();ctx.arc(0,0,f.r+18,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function loop(t){if(!$('#fishModal').classList.contains('on'))return;const dt=Math.min(.04,(t-last)/1000);last=t;const grad=ctx.createLinearGradient(0,0,0,cv.height);grad.addColorStop(0,g.theme[0]);grad.addColorStop(1,g.theme[1]);ctx.fillStyle=grad;ctx.fillRect(0,0,cv.width,cv.height);for(let i=0;i<28;i++){ctx.globalAlpha=.12;ctx.fillStyle=i%3?'#fff':'#4ef';ctx.beginPath();ctx.arc((i*103+t*.02)%cv.width,(i*177)%cv.height,2+i%4,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;const frozen=t<freezeUntil;spawnClock+=dt;formationClock+=dt;aiClock+=dt;if(spawnClock>(.95/g.spawn)/room.pace){spawnClock=0;makeFish(false)}if(formationClock>10/room.pace){formationClock=0;spawnFormation()}if(session.bossProgress>=100&&!session.boss)makeFish(true);if(aiClock>.28){aiClock=0;for(let seat=1;seat<=room.ai;seat++){const candidates=fish.filter(f=>!f.boss||Math.random()<.55);if(candidates.length){const f=candidates[(Math.random()*candidates.length)|0];fireAt(f.x+Math.random()*24-12,f.y+Math.random()*24-12,seat)}}}if(auto&&fish.length&&Math.random()<.5){let f=lock&&lockedId?fish.find(z=>z.id===lockedId):fish[(Math.random()*fish.length)|0];if(f)fireAt(f.x,f.y,0)}for(const f of [...fish]){if(!frozen)f.x+=f.vx*dt;if(f.x<-140||f.x>cv.width+140){if(f.boss)session.boss=null;fish=fish.filter(z=>z!==f);continue}drawTarget(f,t)}for(const s of shotsFx){s.t+=dt;ctx.globalAlpha=Math.max(0,1-s.t*7);ctx.strokeStyle=s.seat===0?'#fff06b':['#ff5d7d','#79ffdc','#b27aff'][s.seat-1]||'#fff';ctx.lineWidth=s.seat===0?4:2;ctx.beginPath();ctx.moveTo(s.x1,s.y1);ctx.lineTo(s.x2,s.y2);ctx.stroke()}shotsFx=shotsFx.filter(s=>s.t<.16);ctx.globalAlpha=1;for(const p of particles){p.t+=dt;ctx.globalAlpha=Math.max(0,1-p.t*2.4);ctx.strokeStyle=['#fff06b','#ff5d7d','#79ffdc','#b27aff'][p.c]||'#fff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,18+p.t*50,0,Math.PI*2);ctx.stroke()}particles=particles.filter(p=>p.t<.4);ctx.globalAlpha=1;ctx.fillStyle='#03121bd6';ctx.fillRect(0,0,cv.width,42);ctx.fillStyle='#d8fbff';ctx.font='bold 18px system-ui';ctx.fillText(`${room.name}   •   ${g.special}   •   HOLD TO RAPID FIRE`,18,27);if(t<bannerUntil){ctx.textAlign='center';ctx.font='900 44px system-ui';ctx.shadowBlur=20;ctx.shadowColor=g.glow;ctx.fillStyle='#fff3b4';ctx.fillText(bannerText,cv.width/2,95);ctx.textAlign='start';ctx.shadowBlur=0}renderFishHud();anim=requestAnimationFrame(loop)}
let si=0,bet=5;const syms=['🐟','🦈','🐙','🔱','💎','🪙','7️⃣','🧜‍♀️','⚓'];window.openSlot=i=>{si=i;const s=slots[i];$('#slotHead').textContent=s.name;$('#slotTitle').textContent=s.name;$('#slotTag').textContent='F.S.A. ORIGINAL';$('#slotDesc').textContent='Five-reel virtual-credit mini game';$('#slotModal').classList.add('on');drawReels()};function drawReels(){const out=Array.from({length:15},()=>syms[(Math.random()*syms.length)|0]);$('#reels').innerHTML=Array.from({length:5},(_,c)=>`<div class="reel">${out.slice(c*3,c*3+3).map(x=>`<div class="sym">${x}</div>`).join('')}</div>`).join('')};window.changeBet=d=>{bet=Math.max(1,Math.min(100,bet+d));$('#bet').textContent=bet};window.spinSlot=()=>{if(profile.credits<bet)return;profile.credits-=bet;drawReels();const win=Math.random()<.28?bet*(2+Math.floor(Math.random()*8)):0;profile.credits+=win;$('#slotResult').textContent=win?`WIN +${win}`:'No win';save()};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});})();