(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const GAMES=[
{name:'Reef Run',world:'Balanced Reef',boss:'Kraken Lord',c1:'#20d9ff',c2:'#755cff',tags:['POPULAR','TREASURE'],event:'Treasure Surge',bossScale:1},
{name:'Dragon Depths',world:'Inferno Hunt',boss:'Inferno Dragon',c1:'#ff5131',c2:'#ffb124',tags:['HOT','BOSS'],event:'Dragon Fury',bossScale:1.1},
{name:"Pirate's Plunder",world:'Treasure Raid',boss:'Dread Kraken',c1:'#23d8ff',c2:'#f3aa2d',tags:['TREASURE','EVENT'],event:'Gold Rush',bossScale:1.08},
{name:'Atlantis Rising',world:'Lost City',boss:'Atlantis Guardian',c1:'#40e7ff',c2:'#e9c45c',tags:['FEATURED','RELIC'],event:'Atlantis Awakens',bossScale:1.12},
{name:'Ice Tide',world:'Glacier World',boss:'Frost Leviathan',c1:'#9eefff',c2:'#437cff',tags:['FREEZE','BOSS'],event:'Deep Freeze',bossScale:1.04},
{name:'Lava Reef',world:'Volcano Run',boss:'Magma Behemoth',c1:'#ff4f26',c2:'#ff9d1a',tags:['HOT','EVENT'],event:'Magma Burst',bossScale:1.1},
{name:'Storm Seas',world:'Tempest Event',boss:'Thunder Leviathan',c1:'#54c5ff',c2:'#8c6cff',tags:['LIGHTNING','HOT'],event:'Storm Surge',bossScale:1.13},
{name:'Jade Dragon',world:'Emerald Temple',boss:'Jade Dragon King',c1:'#3ff08a',c2:'#d8bb47',tags:['ELITE','BOSS'],event:'Dragon Blessing',bossScale:1.16},
{name:'Neon Ocean',world:'Pulse District',boss:'Neon Kraken',c1:'#fb56ea',c2:'#36e9ff',tags:['HOT','FEVER'],event:'Neon Fever',bossScale:.98},
{name:'Ancient Ruins',world:'Relic Expedition',boss:'Ruins Guardian',c1:'#67e5ff',c2:'#d8b05b',tags:['RELIC','EVENT'],event:'Artifact Beam',bossScale:1.14},
{name:'Mecha Marine',world:'Steel Abyss',boss:'Leviathan X',c1:'#3bdfff',c2:'#ff6f34',tags:['ARMORED','BOSS'],event:'EMP Burst',bossScale:1.2},
{name:'Coral Chaos',world:'Prism Gardens',boss:'Prismatic Ray',c1:'#ff6dd8',c2:'#49eff0',tags:['FEATURED','SCHOOLS'],event:'Color Burst',bossScale:1.02},
{name:"Kraken's Lair",world:'Blackwater Boss',boss:'Prime Kraken',c1:'#8158ff',c2:'#ff3f8c',tags:['BOSS','HIGH BET'],event:'Tentacle Storm',bossScale:1.3},
{name:'Treasure Trials',world:'Golden Vault',boss:'Poseidon Reborn',c1:'#ffd34f',c2:'#29d9ff',tags:['TREASURE','JACKPOT'],event:'Vault Surge',bossScale:1.18},
{name:'Boss Rush',world:'Crown Abyss',boss:'Ultimate Legion',c1:'#ff3d54',c2:'#69cfff',tags:['BOSS','HIGH BET'],event:'Overdrive',bossScale:1.55}
];
const SLOT_NAMES=['Ocean Fortune','Treasure Reels',"Siren's Gold",'Legend of Atlantis','Shark Jackpot','Pearl Rush','Kraken Spins','Reef Riches','Lucky Tide','Deep Diamonds','Golden Anchor',"Mermaid's Treasure",'Pirate Jackpot','Coral Cash',"Neptune's Wheel",'Sea King 777','Ocean Wilds','Diamond Dolphin','Wild Pearls','Treasure Temple'];
const SLOT_SETS=[
['🔱','💎','🐚','🐬','👑','7','⭐','💰'],['🧰','🪙','⚓','💎','🏴‍☠️','7','⭐','💰'],['🧜','🐚','💎','🌙','🔱','7','⭐','👑'],['🏛️','🔱','💎','🐠','👑','7','⭐','🌀'],['🦈','💰','💎','⚓','7','⭐','👑','🐚'],['🦪','💎','🐚','🌊','👑','7','⭐','💰'],['🐙','🔱','💎','🌀','⚓','7','⭐','💰'],['🪸','🐠','🐚','💎','👑','7','⭐','💰'],['🍀','🐬','💎','🌊','👑','7','⭐','💰'],['💎','🔷','🐚','🔱','👑','7','⭐','💰'],['⚓','🪙','💎','🌊','👑','7','⭐','💰'],['🧜','💎','🐚','👑','🔱','7','⭐','💰'],['🏴‍☠️','💰','⚓','💎','👑','7','⭐','🧰'],['🪸','💰','🐠','💎','👑','7','⭐','🐚'],['🔱','🌊','💎','👑','🐬','7','⭐','💰'],['👑','🌊','🔱','💎','🐟','7','⭐','💰'],['🌊','🐬','💎','🔱','👑','7','⭐','💰'],['🐬','💎','🌊','👑','🐚','7','⭐','💰'],['🦪','💎','🐚','🌊','👑','7','⭐','💰'],['🏛️','💰','🔱','💎','👑','7','⭐','🐚']
];
const SLOTS=SLOT_NAMES.map((name,i)=>({name,symbols:SLOT_SETS[i],category:i%4===0?'JACKPOT':i%4===1?'OCEAN':i%4===2?'MYTHIC':'TREASURE'}));
const GUNS=[
{name:'Pulse Cannon',icon:'⚡',damage:1.05,rate:105,color:'#29dfff',projectiles:1,role:'precision'},
{name:'Spread Blaster',icon:'💥',damage:.82,rate:185,color:'#ff4e3d',projectiles:3,role:'crowd'},
{name:'Rail Harpoon',icon:'🔱',damage:4.6,rate:410,color:'#ffd04f',projectiles:1,role:'piercing'}
];
const ROOM_BETS=[
[[2,5,10,20,50],[10,20,50,100],[50,100]],
[[10,20,50],[20,50,100,200],[50,100,200,500]],
[[100,200,500],[200,500,1000],[500,1000,2000,5000]]
];
const FISH=[
{name:'Clown Fish',class:'common',mult:3,hp:12,r:28,speed:1.35},
{name:'Blue Tang',class:'fast',mult:5,hp:16,r:31,speed:1.6},
{name:'Puffer',class:'common',mult:10,hp:30,r:36,speed:1},
{name:'Sea Turtle',class:'common',mult:18,hp:46,r:44,speed:.8},
{name:'Chain Ray',class:'chain',mult:28,hp:58,r:52,speed:1.15,hard:true,hpMult:2.8},
{name:'Vortex Jelly',class:'vortex',mult:35,hp:62,r:49,speed:.9,hard:true,hpMult:3.2},
{name:'Shark',class:'armored',mult:50,hp:90,r:64,speed:1.25,hard:true,hpMult:4.5},
{name:'Golden Fish',class:'treasure',mult:80,hp:86,r:52,speed:1.05},
{name:'Bomb Crab',class:'bomb',mult:42,hp:66,r:45,speed:.88},
{name:'Laser Eel',class:'laser',mult:60,hp:78,r:52,speed:1.4,hard:true,hpMult:5.2},
{name:'Drill Fish',class:'drill',mult:70,hp:92,r:57,speed:1.2,hard:true,hpMult:6.2},
{name:'Elite Leviathan',class:'elite',mult:120,hp:170,r:80,speed:.82,hard:true,hpMult:9.5}
];
const ROOMS=[
{name:'Bronze Reef',seats:2,density:.85,reward:.9,hp:1,bossHp:15000},
{name:'Silver Current',seats:3,density:1.05,reward:1,hp:1.55,bossHp:45000},
{name:'Gold Abyss',seats:4,density:1.3,reward:1.14,hp:2.4,bossHp:180000}
];
const net=navigator.connection||navigator.mozConnection||navigator.webkitConnection;
const reduceMotion=matchMedia?.('(prefers-reduced-motion: reduce)')?.matches||false;
const LOW=!!((net&&(net.saveData||/^(slow-)?2g$/.test(net.effectiveType||'')))||reduceMotion||(navigator.deviceMemory&&navigator.deviceMemory<=2)||(navigator.hardwareConcurrency&&navigator.hardwareConcurrency<=2));
const KEY='fsa.v9.profile';
let P={credits:12680450,gems:2480,pearls:36,level:88,xp:4620};try{P={...P,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{}
const st={game:0,room:1,gun:0,betIndex:0,fish:[],shots:[],fx:[],labels:[],players:[],boss:null,bossClock:35,wave:1,waveClock:90,combo:0,fever:82,feverUntil:0,freezeUntil:0,auto:false,autoArmUntil:0,autoSpent:0,autoLimit:0,lock:false,lockArmUntil:0,pointer:{x:640,y:350},last:0,lastShot:0,spawn:0,ai:0,event:0,run:null,raf:0,hold:0,mission:[0,0,0,0],slot:0,slotBet:100,slotAuto:false,slotAutoTimer:0,paused:false};
function save(){try{localStorage.setItem(KEY,JSON.stringify(P))}catch{};['coins','gcoins','slotCoins'].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=Math.floor(P.credits).toLocaleString()});const g=$('#gems');if(g)g.textContent=P.gems.toLocaleString();const q=$('#pearls');if(q)q.textContent=P.pearls.toLocaleString()}
function game(){return GAMES[st.game]}function gun(){return GUNS[st.gun]}function bets(){return ROOM_BETS[st.room][st.gun]}function bet(){return bets()[st.betIndex]}
function clampBetIndex(){st.betIndex=Math.max(0,Math.min(st.betIndex,bets().length-1))}
function art(i){const g=GAMES[i];return `radial-gradient(circle at 70% 30%,${g.c1}88,transparent 28%),radial-gradient(circle at 28% 20%,${g.c2}66,transparent 35%),linear-gradient(145deg,#05243d,#02070d)`}
function filterCards(selector,mode){$$(selector).forEach(card=>{const tags=(card.dataset.tags||'').toUpperCase();card.hidden=mode&&mode!=='ALL'&&!tags.includes(mode)})}
function lobby(){const grid=$('#fishGrid');if(grid){grid.innerHTML=GAMES.map((g,i)=>`<article class="lib-card" data-game="${i}" data-tags="${g.tags.join(' ')} ${i>=12?'HIGH BET':''}" style="--art:${art(i)}"><span class="num">${i+1}</span><div class="meta"><h3>${g.name}</h3><div class="tags"><span>1–4</span><span class="${g.tags.includes('HOT')?'hot':''}">${g.tags[0]}</span><span>${g.world}</span></div></div></article>`).join('');$$('[data-game]').forEach(e=>e.onclick=()=>openGame(+e.dataset.game))}const slots=$('#slotGrid');if(slots){slots.innerHTML=SLOTS.map((s,i)=>`<article class="slot-card" data-slot="${i}" data-tags="${s.category}" style="--c2:${['#143b80','#77224e','#74338a','#1b7791','#8b4c10'][i%5]}99"><b>${s.name}</b><small>${s.category}</small><div class="slot-symbols"><span>${s.symbols[0]}</span><span>${s.symbols[5]}</span><span>${s.symbols[3]}</span></div></article>`).join('');$$('[data-slot]').forEach(e=>e.onclick=()=>openSlot(+e.dataset.slot))}$$('#fishgames .filters button').forEach(b=>b.onclick=()=>filterCards('.lib-card',b.textContent.trim().replace('FEATURED','FEATURED').replace('HIGH BET','HIGH BET')));$$('#slots .filters button').forEach(b=>b.onclick=()=>filterCards('.slot-card',b.textContent.trim()));save()}
function openGame(i){st.game=i;$('#game').classList.add('on');$('#gameName').textContent=game().name;$('#gameWorld').textContent=game().world;$('#bossName').textContent=game().boss;chooseRoom(st.room);cancelAnimationFrame(st.raf);st.last=performance.now();st.paused=false;st.raf=requestAnimationFrame(loop)}window.openGame=openGame;
function closeGame(){disableAuto('Auto fire off');st.lock=false;$('#game').classList.remove('on');cancelAnimationFrame(st.raf);clearInterval(st.hold)}window.closeGame=closeGame;
function makePlayers(){const own=bet();return [
{name:'YOU',balance:P.credits,color:'#28d7ff',gun:st.gun,bet:own},
{name:'Player 2',balance:2480300,color:'#ff3d4e',gun:1,bet:ROOM_BETS[st.room][1][Math.min(1,ROOM_BETS[st.room][1].length-1)]},
{name:'Player 3',balance:5610000,color:'#ffd14f',gun:2,bet:ROOM_BETS[st.room][2][Math.min(1,ROOM_BETS[st.room][2].length-1)]},
{name:'Player 4',balance:320450,color:'#23e899',gun:0,bet:ROOM_BETS[st.room][0][0]}
]}
function chooseRoom(i){st.room=Math.max(0,Math.min(ROOMS.length-1,+i||0));st.gun=0;st.betIndex=0;st.fish=[];st.shots=[];st.fx=[];st.labels=[];st.boss=null;st.bossClock=st.game===14?9:22+Math.random()*22;st.wave=1;st.waveClock=90;st.combo=0;st.fever=82;st.feverUntil=0;st.auto=false;st.autoSpent=0;st.lock=false;st.mission=[0,0,0,0];st.run={shots:0,hits:0,kills:0,score:0};st.players=makePlayers();for(let n=0;n<(LOW?8:18);n++)spawn();updateWeapon();banner(`${ROOMS[st.room].name} · ${game().world}`);emitFeed(`Entered ${ROOMS[st.room].name}`);hud()}window.chooseRoom=chooseRoom;
function spawn(boss=false){if(boss){const hp=Math.round(ROOMS[st.room].bossHp*game().bossScale*(1+(st.wave-1)*.08));const f={id:Math.random(),name:game().boss,class:'boss',boss:true,lifeBar:true,mult:800+st.game*20,hp,max:hp,r:145,x:1320,y:285,vx:-(16+st.room*2),vy:0,phase:0};st.fish.push(f);st.boss=f;banner(`BOSS INCOMING · ${f.name}`);emitFeed(`${f.name} entered · ${hp.toLocaleString()} HP`);return}const t=FISH[Math.random()*FISH.length|0],dir=Math.random()<.8?-1:1;const baseHp=t.hp*ROOMS[st.room].hp*(t.hard?(t.hpMult||3):1);const hp=Math.max(1,Math.round(baseHp*(1+(st.wave-1)*.035)));st.fish.push({id:Math.random(),name:t.name,class:t.class,mult:t.mult,hp,max:hp,r:t.r,x:dir<0?1320:-70,y:70+Math.random()*560,vx:dir*(55+Math.random()*90)*t.speed,vy:(Math.random()-.5)*20,phase:Math.random()*6.2,lifeBar:!!t.hard,hard:!!t.hard})}
function switchGun(i){st.gun=Math.max(0,Math.min(GUNS.length-1,+i||0));st.betIndex=0;disableAuto('Auto fire disabled after weapon change');if(st.players[0]){st.players[0].gun=st.gun;st.players[0].bet=bet()}updateWeapon();banner(gun().name)}window.switchGun=switchGun;
function betStep(d){st.betIndex=Math.max(0,Math.min(bets().length-1,st.betIndex+(d>0?1:-1)));disableAuto('Auto fire disabled after shot-value change');if(st.players[0])st.players[0].bet=bet();updateWeapon()}window.betStep=betStep;
function updateWeapon(){clampBetIndex();const g=gun();$$('.weapon-switch button').slice(0,3).forEach((b,i)=>b.classList.toggle('on',i===st.gun));$('#youGun').textContent=g.name;$('#youBet').textContent=bet().toLocaleString();$('#youGunArt').textContent=g.icon;$('#youSeat').style.setProperty('--seat',g.color);if(st.players[0]){st.players[0].gun=st.gun;st.players[0].bet=bet()}}
function targetAt(x,y){let best=null,dist=Infinity;for(const f of st.fish){const d=Math.hypot(f.x-x,f.y-y);if(d<f.r*1.35&&d<dist){best=f;dist=d}}return best}
function bestTarget(){return [...st.fish].sort((a,b)=>((b.boss?100000:b.hard?10000:b.mult))-((a.boss?100000:a.hard?10000:a.mult)))[0]}
function playerGun(seat){return GUNS[st.players[seat]?.gun??0]}
function shotCost(seat){return Math.max(1,Math.round(st.players[seat]?.bet||bet()))}
function shoot(x,y,seat=0){if(!st.run||st.paused)return false;const pl=st.players[seat],g=playerGun(seat),cost=shotCost(seat);const now=performance.now();if(seat===0&&now-st.lastShot<g.rate)return false;if(!pl||pl.balance<cost){if(seat===0)disableAuto('Auto fire stopped · insufficient credits');return false}if(seat===0&&st.auto&&st.autoSpent+cost>st.autoLimit){disableAuto('Auto fire stopped · spend limit reached');return false}pl.balance-=cost;if(seat===0){P.credits=pl.balance;st.run.shots++;st.lastShot=now;if(st.auto)st.autoSpent+=cost;save()}let target=st.lock&&seat===0?bestTarget():targetAt(x,y);if(st.lock&&seat===0&&target){x=target.x;y=target.y}const starts=[[640,700],[180,700],[1100,700],[640,15]],s=starts[seat]||starts[0],count=g.projectiles;for(let q=0;q<count;q++){const off=(q-(count-1)/2)*30;st.shots.push({x:s[0],y:s[1],tx:x+off,ty:y+off*.25,t:0,c:pl.color,w:pl.gun===2?7:3})}if(target){let dmg=cost*g.damage*(.92+Math.random()*.22);if(pl.gun===1)dmg*=1.35;if(pl.gun===2&&target.hard)dmg*=1.25;hit(target,dmg,seat);if(pl.gun===1){st.fish.filter(f=>f!==target&&Math.hypot(f.x-target.x,f.y-target.y)<155).slice(0,2).forEach(f=>hit(f,dmg*.45,seat))}if(pl.gun===2){st.fish.filter(f=>f!==target&&Math.abs(f.y-target.y)<65).slice(0,3).forEach(f=>hit(f,dmg*.32,seat))}}return true}
function hit(f,dmg,seat){if(!f||f.hp<=0)return;f.hp-=dmg;st.fx.push({x:f.x,y:f.y,t:0,c:st.players[seat]?.color||gun().color});if(seat===0){st.run.hits++;st.combo++;st.fever=Math.min(100,st.fever+.9);if(st.fever>=100&&Date.now()>st.feverUntil){st.fever=0;st.feverUntil=Date.now()+9000;st.mission[3]=1;banner('OCEAN FEVER · REWARD ×2')}}if(f.hp<=0)kill(f,seat)}
function kill(f,seat){const pl=st.players[seat],reward=Math.round(shotCost(seat)*f.mult*ROOMS[st.room].reward*(seat===0&&Date.now()<st.feverUntil?2:1));pl.balance+=reward;if(seat===0){P.credits=pl.balance;st.run.kills++;st.run.score+=reward;st.mission[0]++;st.labels.push({x:f.x,y:f.y,t:0,text:`+${reward.toLocaleString()}`});save()}if(f.boss){if(seat===0)st.mission[1]++;banner(`${seat===0?'YOU':pl.name} defeated ${f.name} · +${reward.toLocaleString()}`);st.boss=null;st.bossClock=st.game===14?10:34;emitFeed(`${pl.name} landed the finishing shot on ${f.name}`)}else if(f.hard){if(seat===0)st.mission[2]++;emitFeed(`${pl.name} took down ${f.name} ×${f.mult}`)}st.fish=st.fish.filter(x=>x!==f)}
function power(type){if(!st.run)return;if(type==='freeze'){st.freezeUntil=Date.now()+5000;banner('DEEP FREEZE')}if(type==='lightning'){st.fish.slice(0,8).forEach(f=>hit(f,bet()*3.2,0));banner('LIGHTNING CHAIN')}if(type==='bomb'){st.fish.slice().forEach(f=>hit(f,Math.max(20,f.max*.2),0));banner('DEPTH BOMB')}if(type==='nuke'){st.fish.filter(f=>!f.boss).slice(0,12).forEach(f=>hit(f,f.max+1,0));banner('TORNADO CLEAR')}}window.power=power;
function banner(t){const b=$('#battleMsg');if(!b)return;b.textContent=t;b.classList.add('on');clearTimeout(b._t);b._t=setTimeout(()=>b.classList.remove('on'),1900)}
function emitFeed(t){const f=$('#liveFeed');if(f)f.innerHTML=`<div class="live-row"><span>${t}</span><em>LIVE</em></div>`+f.innerHTML.slice(0,1100)}
function disableAuto(message){st.auto=false;st.autoArmUntil=0;st.autoSpent=0;st.autoLimit=0;const b=$('#autoBtn');if(b)b.textContent='AUTO FIRE';if(message&&$('#game')?.classList.contains('on'))banner(message)}
function armAuto(){const now=Date.now();if(st.auto){disableAuto('Auto fire off');return}if(now<st.autoArmUntil){st.auto=true;st.autoArmUntil=0;st.autoSpent=0;st.autoLimit=bet()*50;$('#autoBtn').textContent='AUTO ON';banner(`AUTO ON · ${st.autoLimit.toLocaleString()} CREDIT LIMIT`);return}st.autoArmUntil=now+3000;$('#autoBtn').textContent='TAP AGAIN';banner('AUTO FIRE ARMED · TAP AGAIN TO CONFIRM')}
function armLock(){const now=Date.now();if(st.lock){st.lock=false;st.lockArmUntil=0;$('#lockBtn').textContent='LOCK ON';banner('LOCK OFF');return}if(now<st.lockArmUntil){st.lock=true;st.lockArmUntil=0;$('#lockBtn').textContent='LOCKED';banner('LOCK ON CONFIRMED');return}st.lockArmUntil=now+3000;$('#lockBtn').textContent='TAP AGAIN';banner('LOCK ARMED · TAP AGAIN TO CONFIRM')}
function drawFishShape(x,f,g){const c=f.hard?g.c2:g.c1;x.save();x.translate(f.x,f.y+Math.sin(f.phase)*4);if(f.vx>0)x.scale(-1,1);x.shadowBlur=LOW?0:(f.hard?16:8);x.shadowColor=c;x.fillStyle=c;x.strokeStyle='#dffcff';x.lineWidth=2;if(f.class==='vortex'){x.beginPath();x.arc(0,0,f.r*.62,Math.PI,0);x.quadraticCurveTo(f.r*.6,f.r*.55,0,f.r*.52);x.quadraticCurveTo(-f.r*.6,f.r*.55,-f.r*.62,0);x.fill();for(let i=-2;i<=2;i++){x.beginPath();x.moveTo(i*f.r*.18,f.r*.35);x.quadraticCurveTo(i*f.r*.3,f.r*.8,i*f.r*.12,f.r*1.1);x.stroke()}}else if(f.class==='chain'){x.beginPath();x.moveTo(f.r*1.25,0);x.quadraticCurveTo(0,-f.r*.8,-f.r*1.25,0);x.quadraticCurveTo(0,f.r*.8,f.r*1.25,0);x.fill();x.beginPath();x.moveTo(-f.r*.7,0);x.lineTo(-f.r*1.45,-f.r*.28);x.lineTo(-f.r*1.45,f.r*.28);x.closePath();x.fill()}else if(f.class==='laser'||f.class==='drill'){x.beginPath();x.ellipse(0,0,f.r*1.15,f.r*.42,0,0,Math.PI*2);x.fill();x.beginPath();x.moveTo(-f.r,0);x.lineTo(-f.r*1.45,-f.r*.42);x.lineTo(-f.r*1.38,f.r*.42);x.closePath();x.fill();x.strokeStyle=f.class==='laser'?'#ff715d':'#ffe26b';x.lineWidth=4;x.beginPath();x.moveTo(-f.r*.6,0);x.lineTo(f.r*.65,0);x.stroke()}else if(f.class==='elite'){x.beginPath();x.ellipse(0,0,f.r*1.22,f.r*.52,0,0,Math.PI*2);x.fill();x.fillStyle='#ffffff35';x.beginPath();x.ellipse(f.r*.15,-f.r*.18,f.r*.58,f.r*.18,0,0,Math.PI*2);x.fill();x.fillStyle=c;x.beginPath();x.moveTo(-f.r*.95,0);x.lineTo(-f.r*1.55,-f.r*.48);x.lineTo(-f.r*1.45,f.r*.48);x.closePath();x.fill()}else if(f.class==='bomb'){x.beginPath();x.arc(0,0,f.r*.65,0,Math.PI*2);x.fill();for(let i=0;i<6;i++){const a=i*Math.PI/3;x.beginPath();x.moveTo(Math.cos(a)*f.r*.55,Math.sin(a)*f.r*.55);x.lineTo(Math.cos(a)*f.r,Math.sin(a)*f.r);x.stroke()}}else{x.beginPath();x.ellipse(0,0,f.r*1.05,f.r*.55,0,0,Math.PI*2);x.fill();x.beginPath();x.moveTo(-f.r*.9,0);x.lineTo(-f.r*1.42,-f.r*.5);x.lineTo(-f.r*1.34,f.r*.5);x.closePath();x.fill();x.fillStyle='#fff';x.beginPath();x.arc(f.r*.58,-f.r*.13,f.r*.1,0,Math.PI*2);x.fill();x.fillStyle='#061018';x.beginPath();x.arc(f.r*.61,-f.r*.13,f.r*.045,0,Math.PI*2);x.fill()}x.restore()}
function drawBoss(x,f,g){x.save();x.translate(f.x,f.y+Math.sin(f.phase)*3);x.shadowBlur=LOW?0:28;x.shadowColor=g.c2;x.fillStyle=g.c2;x.strokeStyle=g.c1;x.lineWidth=8;if(st.game%3===1||st.game===7){x.beginPath();for(let i=0;i<7;i++){const xx=-f.r*1.1+i*f.r*.36,yy=Math.sin(i+f.phase)*f.r*.25;i?x.lineTo(xx,yy):x.moveTo(xx,yy)}x.stroke();x.beginPath();x.moveTo(f.r*1.35,0);x.lineTo(f.r*.65,-f.r*.45);x.lineTo(f.r*.7,f.r*.45);x.closePath();x.fill()}else{x.beginPath();x.arc(0,-f.r*.12,f.r*.6,0,Math.PI*2);x.fill();for(let i=0;i<8;i++){const a=-2.8+i*.38;x.beginPath();x.moveTo(Math.cos(a)*f.r*.28,0);x.quadraticCurveTo(Math.cos(a)*f.r,f.r*.7,Math.cos(a+.4)*f.r*1.35,f.r*1.1);x.stroke()}}x.restore()}
function draw(now){const c=$('#battleCanvas'),x=c.getContext('2d'),w=c.width,h=c.height,g=game();x.clearRect(0,0,w,h);const gr=x.createLinearGradient(0,0,0,h);gr.addColorStop(0,'#063b5b');gr.addColorStop(.45,g.c1+'33');gr.addColorStop(1,'#01060b');x.fillStyle=gr;x.fillRect(0,0,w,h);x.globalAlpha=.18;x.fillStyle=g.c2;for(let i=0;i<8;i++){x.beginPath();x.moveTo(i*180,0);x.lineTo(i*180+170,h);x.lineTo(i*180+260,h);x.fill()}x.globalAlpha=1;if(!LOW){for(let i=0;i<20;i++){x.fillStyle=i%2?g.c1+'55':g.c2+'44';x.beginPath();x.arc((i*93+now*.018)%w,50+(i*127)%590,2+i%4,0,7);x.fill()}}for(const f of st.fish){f.boss?drawBoss(x,f,g):drawFishShape(x,f,g);x.textAlign='center';x.font=`900 ${f.boss?25:15}px system-ui`;x.strokeStyle='#02070d';x.lineWidth=4;x.strokeText('×'+f.mult,f.x,f.y+f.r*.85);x.fillStyle='#ffd353';x.fillText('×'+f.mult,f.x,f.y+f.r*.85);if(f.boss||f.lifeBar){const bw=f.boss?170:Math.max(82,Math.min(126,f.r*1.75)),bh=f.boss?9:7,bx=f.x-bw/2,by=f.y-f.r*.9;x.fillStyle='#02070de6';x.fillRect(bx-2,by-2,bw+4,bh+4);x.fillStyle=f.boss?'#ff3048':'#ffb52f';x.fillRect(bx,by,bw*Math.max(0,f.hp/f.max),bh);x.strokeStyle=f.boss?'#ff8062':'#ffe17a';x.lineWidth=1;x.strokeRect(bx,by,bw,bh)}}for(const s of st.shots){x.save();x.globalAlpha=Math.max(0,1-s.t*2);x.strokeStyle=s.c;x.lineWidth=s.w;x.shadowBlur=LOW?0:14;x.shadowColor=s.c;x.beginPath();x.moveTo(s.x,s.y);x.lineTo(s.tx,s.ty);x.stroke();x.restore()}for(const f of st.fx){x.globalAlpha=Math.max(0,1-f.t*2);x.strokeStyle=f.c;x.lineWidth=3;x.beginPath();x.arc(f.x,f.y,10+f.t*55,0,7);x.stroke()}x.globalAlpha=1;for(const l of st.labels){x.globalAlpha=Math.max(0,1-l.t*1.2);x.fillStyle='#ffd34d';x.font='900 23px system-ui';x.textAlign='center';x.fillText(l.text,l.x,l.y-l.t*42)}x.globalAlpha=1;if(st.lock&&st.fish.length){const f=bestTarget();x.strokeStyle='#ff3a40';x.lineWidth=3;x.setLineDash([8,7]);x.beginPath();x.arc(f.x,f.y,f.r*1.4,0,7);x.stroke();x.setLineDash([]);x.fillStyle='#ff6a58';x.font='900 11px system-ui';x.fillText('LOCK ON',f.x,f.y+6)}}
function hud(){if(!st.run)return;$('#bossHP').style.width=(st.boss?Math.max(0,st.boss.hp/st.boss.max*100):0)+'%';$('#bossText').textContent=st.boss?`${Math.max(0,Math.floor(st.boss.hp)).toLocaleString()} / ${st.boss.max.toLocaleString()}`:'INCOMING';$('#timeLeft').textContent=`0${Math.floor(st.waveClock/60)}:${String(Math.max(0,Math.floor(st.waveClock%60))).padStart(2,'0')}`;$('#combo').textContent=st.combo;$('#fever').style.width=st.fever+'%';$('#feverPct').textContent=Math.floor(st.fever)+'%';$('#mCatch').textContent=st.mission[0]+'/50';$('#mBoss').textContent=st.mission[1]+'/3';$('#mChest').textContent=st.mission[2]+'/5';const feverMission=$$('.gmission').find(e=>e.textContent.includes('Trigger Ocean Fever'));if(feverMission)feverMission.querySelector('b').textContent=st.mission[3]+'/1';$('#radar').querySelectorAll('.dot').forEach(d=>d.remove());st.fish.slice(0,LOW?10:24).forEach(f=>{const d=document.createElement('i');d.className='dot';d.style.left=(8+84*f.x/1280)+'%';d.style.top=(8+84*f.y/720)+'%';d.style.background=f.boss?'#ff3144':f.hard?'#ffd24e':'#33dcff';$('#radar').appendChild(d)});$$('.seatgun').forEach((e,i)=>{const b=e.querySelector('.bal');if(b)b.textContent=Math.floor(st.players[i]?.balance||0).toLocaleString()})}
function loop(n){if(!$('#game').classList.contains('on')||st.paused)return;const dt=Math.min(.05,(n-st.last)/1000||.016);st.last=n;st.spawn+=dt;st.ai+=dt;st.event+=dt;st.waveClock-=dt;st.bossClock-=dt;const slow=Date.now()<st.freezeUntil?.15:1;st.fish.forEach(f=>{f.phase+=dt*2;f.x+=f.vx*dt*slow;f.y+=f.vy*dt*slow});st.fish=st.fish.filter(f=>f.x>-220&&f.x<1500&&f.y>-120&&f.y<840);if(st.spawn>Math.max(.3,.78/ROOMS[st.room].density)){st.spawn=0;if(st.fish.length<(LOW?16:42))spawn()}if(st.bossClock<=0&&!st.boss)spawn(true);if(st.waveClock<=0){st.wave++;st.waveClock=90;banner(`WAVE ${st.wave} · ${game().world}`)}if(st.event>(st.game===14?18:30)){st.event=0;banner(game().event);for(let i=0;i<(LOW?2:5);i++)spawn()}if(st.ai>.68){st.ai=0;for(let s=1;s<ROOMS[st.room].seats;s++){const f=st.fish[Math.random()*st.fish.length|0];if(f)shoot(f.x,f.y,s)}}if(st.auto&&st.fish.length&&n-st.lastShot>gun().rate){const f=bestTarget();shoot(f.x,f.y,0)}if(st.combo&&Math.random()<dt*.18)st.combo--;st.shots.forEach(s=>s.t+=dt);st.shots=st.shots.filter(s=>s.t<.55);st.fx.forEach(f=>f.t+=dt);st.fx=st.fx.filter(f=>f.t<.5);st.labels.forEach(l=>l.t+=dt);st.labels=st.labels.filter(l=>l.t<.9);draw(n);hud();st.raf=requestAnimationFrame(loop)}
function bindGame(){const c=$('#battleCanvas');const point=e=>{const r=c.getBoundingClientRect();st.pointer.x=(e.clientX-r.left)*1280/r.width;st.pointer.y=(e.clientY-r.top)*720/r.height};c.onpointermove=point;c.onpointerdown=e=>{point(e);shoot(st.pointer.x,st.pointer.y,0);clearInterval(st.hold);st.hold=setInterval(()=>shoot(st.pointer.x,st.pointer.y,0),LOW?260:130)};['pointerup','pointerleave','pointercancel'].forEach(k=>c.addEventListener(k,()=>clearInterval(st.hold)));$('#autoBtn').onclick=armAuto;$('#lockBtn').onclick=armLock;$('#leftToggle').onclick=()=>$('#leftHud').classList.toggle('open');$('#rightToggle').onclick=()=>$('#rightHud').classList.toggle('open');document.addEventListener('visibilitychange',()=>{st.paused=document.hidden;if(document.hidden){clearInterval(st.hold);cancelAnimationFrame(st.raf)}else if($('#game').classList.contains('on')){st.last=performance.now();st.raf=requestAnimationFrame(loop)}})}
function openSlot(i){st.slot=i;$('#slotModal').classList.add('on');$('#slotTitle').textContent=SLOTS[i].name;$('#slotBet').textContent=st.slotBet;spin(false)}window.openSlot=openSlot;
window.closeSlot=()=>{st.slotAuto=false;clearTimeout(st.slotAutoTimer);$('#slotModal').classList.remove('on')};
window.slotBet=d=>{st.slotBet=Math.max(10,Math.min(5000,st.slotBet+(d>0?50:-50)));$('#slotBet').textContent=st.slotBet};
function spin(pay=true){const slot=SLOTS[st.slot];if(pay){if(P.credits<st.slotBet)return;P.credits-=st.slotBet}const vals=[];$$('.reel').forEach(r=>{const v=slot.symbols[Math.random()*slot.symbols.length|0];r.textContent=v;vals.push(v)});let win=0;const counts=Object.fromEntries(vals.map(v=>[v,vals.filter(x=>x===v).length]));const best=Math.max(...Object.values(counts));if(best>=3)win=st.slotBet*(best===5?15:best===4?8:4);if(vals.filter(v=>v==='7').length>=3)win=Math.max(win,st.slotBet*12);if(vals.filter(v=>v==='⭐').length>=3)win=Math.max(win,st.slotBet*6);if(win){P.credits+=win;$('#slotResult').textContent=`${slot.category} WIN +${win.toLocaleString()}`}else $('#slotResult').textContent=pay?'No line win. Spin again.':`${slot.category} · Ready.`;save();if(st.slotAuto&&pay){st.slotAutoTimer=setTimeout(()=>spin(true),650)}}window.spin=()=>spin(true);
function toggleSlotAuto(){st.slotAuto=!st.slotAuto;const b=$('#slotAutoBtn');if(b)b.textContent=st.slotAuto?'AUTO ON':'AUTO';clearTimeout(st.slotAutoTimer);if(st.slotAuto)spin(true)}
function ensureSlotAutoButton(){const controls=$('.slot-controls');if(controls&&!$('#slotAutoBtn')){const b=document.createElement('button');b.className='btn';b.id='slotAutoBtn';b.textContent='AUTO';b.onclick=toggleSlotAuto;controls.insertBefore(b,controls.querySelector('.primary'))}}
function init(){lobby();bindGame();ensureSlotAutoButton();$$('[data-scroll]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'}));setInterval(()=>{const e=$('#eventTimer');if(e){const s=Math.floor(Date.now()/1000)%86400,r=86400-s;e.textContent=String(Math.floor(r/3600)).padStart(2,'0')+':'+String(Math.floor((r%3600)/60)).padStart(2,'0')+':'+String(r%60).padStart(2,'0')}},1000);save()}
window.__FSA_GAME_TEST__={GAMES,SLOTS,GUNS,ROOM_BETS,FISH,ROOMS,lowMode:LOW,getState:()=>st,getProfile:()=>P,selectRoom:i=>{st.room=i;st.gun=0;st.betIndex=0;return bet()},selectGun:i=>{st.gun=i;st.betIndex=0;return bets()},bossHp:(gameIndex,roomIndex,wave=1)=>Math.round(ROOMS[roomIndex].bossHp*GAMES[gameIndex].bossScale*(1+(wave-1)*.08))};
init();
})();