(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const GAMES=[
['Reef Run','Balanced Reef','Kraken Lord','#20d9ff','#755cff','🐠'],['Dragon Depths','Inferno Hunt','Inferno Dragon','#ff5131','#ffb124','🐉'],["Pirate's Plunder",'Treasure Raid','Dread Kraken','#23d8ff','#f3aa2d','🏴‍☠️'],['Atlantis Rising','Lost City','Atlantis Guardian','#40e7ff','#e9c45c','🏛️'],['Ice Tide','Glacier World','Frost Leviathan','#9eefff','#437cff','🧊'],['Lava Reef','Volcano Run','Magma Behemoth','#ff4f26','#ff9d1a','🌋'],['Storm Seas','Tempest Event','Thunder Leviathan','#54c5ff','#8c6cff','⚡'],['Jade Dragon','Emerald Temple','Jade Dragon King','#3ff08a','#d8bb47','🐲'],['Neon Ocean','Pulse District','Neon Kraken','#fb56ea','#36e9ff','🪼'],['Ancient Ruins','Relic Expedition','Ruins Guardian','#67e5ff','#d8b05b','🗿'],['Mecha Marine','Steel Abyss','Leviathan X','#3bdfff','#ff6f34','🤖'],['Coral Chaos','Prism Gardens','Prismatic Ray','#ff6dd8','#49eff0','🪸'],["Kraken's Lair",'Blackwater Boss','Prime Kraken','#8158ff','#ff3f8c','🐙'],['Treasure Trials','Golden Vault','Poseidon Reborn','#ffd34f','#29d9ff','💰'],['Boss Rush','Crown Abyss','Ultimate Legion','#ff3d54','#69cfff','👹']];
const SLOTS=['Ocean Fortune','Treasure Reels',"Siren's Gold",'Legend of Atlantis','Shark Jackpot','Pearl Rush','Kraken Spins','Reef Riches','Lucky Tide','Deep Diamonds','Golden Anchor',"Mermaid's Treasure",'Pirate Jackpot','Coral Cash',"Neptune's Wheel",'Sea King 777','Ocean Wilds','Diamond Dolphin','Wild Pearls','Treasure Temple'];
const GUNS=[
{name:'Pulse Cannon',icon:'⚡',mult:1,damage:1.05,rate:105,color:'#29dfff',bets:[2,5,10,20,50]},
{name:'Spread Blaster',icon:'💥',mult:3,damage:.78,rate:185,color:'#ff4e3d',bets:[10,20,50,100,200]},
{name:'Rail Harpoon',icon:'🔱',mult:10,damage:4.6,rate:410,color:'#ffd04f',bets:[50,100,200,500,1000]}
];
const FISH=[
{name:'Clown Fish',icon:'🐠',mult:3,hp:12,r:28,speed:1.35},
{name:'Blue Tang',icon:'🐟',mult:5,hp:16,r:31,speed:1.6},
{name:'Puffer',icon:'🐡',mult:10,hp:30,r:36,speed:1},
{name:'Sea Turtle',icon:'🐢',mult:18,hp:46,r:44,speed:.8},
{name:'Chain Ray',icon:'🛸',mult:28,hp:58,r:52,speed:1.15,hard:true,hpMult:2.8},
{name:'Vortex Jelly',icon:'🪼',mult:35,hp:62,r:49,speed:.9,hard:true,hpMult:3.2},
{name:'Shark',icon:'🦈',mult:50,hp:90,r:64,speed:1.25,hard:true,hpMult:4.5},
{name:'Golden Fish',icon:'🐟',mult:80,hp:86,r:52,speed:1.05},
{name:'Bomb Crab',icon:'🦀',mult:42,hp:66,r:45,speed:.88},
{name:'Laser Eel',icon:'🐍',mult:60,hp:78,r:52,speed:1.4,hard:true,hpMult:5.2},
{name:'Drill Fish',icon:'🐬',mult:70,hp:92,r:57,speed:1.2,hard:true,hpMult:6.2},
{name:'Elite Leviathan',icon:'🐋',mult:120,hp:170,r:80,speed:.82,hard:true,hpMult:9.5}
];
const ROOMS=[{name:'Bronze Reef',min:1,max:100,seats:2,density:.85,reward:.9},{name:'Silver Current',min:10,max:500,seats:3,density:1.05,reward:1},{name:'Gold Abyss',min:100,max:5000,seats:4,density:1.3,reward:1.14}];
const net=navigator.connection||navigator.mozConnection||navigator.webkitConnection;const LOW=!!(net&&(net.saveData||/^(slow-)?2g$/.test(net.effectiveType||'')));
const KEY='fsa.v9.profile';let P={credits:12680450,gems:2480,pearls:36,level:88,xp:4620};try{P={...P,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{}
const st={game:0,room:1,gun:0,bet:2,fish:[],shots:[],fx:[],labels:[],players:[],boss:null,bossClock:35,wave:1,waveClock:90,combo:0,fever:82,feverUntil:0,freezeUntil:0,auto:false,lock:false,pointer:{x:640,y:350},last:0,lastShot:0,spawn:0,ai:0,run:null,raf:0,mission:[0,0,0,0],slot:0,slotBet:100};
function save(){try{localStorage.setItem(KEY,JSON.stringify(P))}catch{};['coins','gcoins','slotCoins'].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=Math.floor(P.credits).toLocaleString()});const g=$('#gems');if(g)g.textContent=P.gems.toLocaleString();const q=$('#pearls');if(q)q.textContent=P.pearls.toLocaleString()}
function art(i){const g=GAMES[i];return `radial-gradient(circle at 70% 30%,${g[3]}88,transparent 28%),radial-gradient(circle at 28% 20%,${g[4]}66,transparent 35%),linear-gradient(145deg,#05243d,#02070d)`}
function lobby(){const grid=$('#fishGrid');if(grid){grid.innerHTML=GAMES.map((g,i)=>`<article class="lib-card" data-game="${i}" style="--art:${art(i)}"><span class="num">${i+1}</span><div class="meta"><h3>${g[0]}</h3><div class="tags"><span>1–4</span><span class="${i%4===1?'hot':''}">${i%4===0?'POPULAR':i%4===1?'HOT':i%4===2?'BOSS':'EVENT'}</span><span>${g[1]}</span></div></div></article>`).join('');$$('[data-game]').forEach(e=>e.onclick=()=>openGame(+e.dataset.game))}const slots=$('#slotGrid');if(slots){slots.innerHTML=SLOTS.map((s,i)=>`<article class="slot-card" data-slot="${i}" style="--c2:${['#143b80','#77224e','#74338a','#1b7791','#8b4c10'][i%5]}99"><b>${s}</b><small>${i%3===0?'JACKPOT':i%3===1?'DELUXE':'OCEAN CLASSIC'}</small><div class="slot-symbols"><span>${['💎','🔱','🐚','🪸','⭐'][i%5]}</span><span>7</span><span>${['🐬','👑','🧜','⚓','💰'][i%5]}</span></div></article>`).join('');$$('[data-slot]').forEach(e=>e.onclick=()=>openSlot(+e.dataset.slot))}save()}
function openGame(i){st.game=i;$('#game').classList.add('on');$('#gameName').textContent=GAMES[i][0];$('#gameWorld').textContent=GAMES[i][1];$('#bossName').textContent=GAMES[i][2];chooseRoom(st.room);cancelAnimationFrame(st.raf);st.last=performance.now();st.raf=requestAnimationFrame(loop)}window.openGame=openGame;
function closeGame(){$('#game').classList.remove('on');cancelAnimationFrame(st.raf)}window.closeGame=closeGame;
function chooseRoom(i){st.room=i;st.gun=0;st.bet=2;st.fish=[];st.shots=[];st.fx=[];st.labels=[];st.boss=null;st.bossClock=22+Math.random()*22;st.wave=1;st.waveClock=90;st.combo=0;st.fever=82;st.run={shots:0,hits:0,kills:0,score:0};st.players=[['YOU',P.credits,'#28d7ff'],['Player 2',2480300,'#ff3d4e'],['Player 3',5610000,'#ffd14f'],['Player 4',320450,'#23e899']];for(let n=0;n<(LOW?8:18);n++)spawn();updateWeapon();banner(ROOMS[i].name+' · '+GAMES[st.game][1]);emitFeed('Entered '+ROOMS[i].name)}window.chooseRoom=chooseRoom;
function spawn(boss=false){if(boss){const g=GAMES[st.game],f={id:Math.random(),name:g[2],icon:g[5],boss:true,lifeBar:true,mult:800,hp:10000000,max:10000000,r:145,x:1320,y:285,vx:-18,vy:0,phase:0};st.fish.push(f);st.boss=f;banner('BOSS INCOMING · '+f.name);return}const t=FISH[Math.random()*FISH.length|0],dir=Math.random()<.8?-1:1,roomScale=16+st.room*8,hardScale=t.hard?(t.hpMult||3):1,hp=t.mult*roomScale*hardScale;st.fish.push({id:Math.random(),name:t.name,icon:t.icon,mult:t.mult,hp,max:hp,r:t.r,x:dir<0?1320:-70,y:70+Math.random()*560,vx:dir*(55+Math.random()*90)*t.speed,vy:(Math.random()-.5)*20,phase:Math.random()*6.2,lifeBar:!!t.hard,hard:!!t.hard})}
function gun(){return GUNS[st.gun]}function bet(){return gun().bets[st.bet]}
function switchGun(i){st.gun=i;st.bet=Math.min(st.bet,gun().bets.length-1);updateWeapon();banner(gun().name)}window.switchGun=switchGun;
function betStep(d){st.bet=Math.max(0,Math.min(gun().bets.length-1,st.bet+d));updateWeapon()}window.betStep=betStep;
function updateWeapon(){const g=gun();$$('.weapon-switch button').slice(0,3).forEach((b,i)=>b.classList.toggle('on',i===st.gun));$('#youGun').textContent=g.name;$('#youBet').textContent=bet().toLocaleString();$('#youGunArt').textContent=g.icon;$('#youSeat').style.setProperty('--seat',g.color)}
function targetAt(x,y){return st.fish.find(f=>Math.hypot(f.x-x,f.y-y)<f.r*1.35)}
function bestTarget(){return [...st.fish].sort((a,b)=>((b.boss?100000:b.hard?10000:b.mult))-((a.boss?100000:a.hard?10000:a.mult)))[0]}
function shoot(x,y,seat=0){if(!st.run)return;const g=gun(),cost=seat?Math.max(50,bet()*.6):bet()*g.mult;if(!seat){if(P.credits<cost)return;const now=performance.now();if(now-st.lastShot<g.rate)return;st.lastShot=now;P.credits-=cost;st.run.shots++;save()}let target=st.lock?bestTarget():targetAt(x,y);if(st.lock&&target){x=target.x;y=target.y}const starts=[[640,700],[180,700],[1100,700],[640,15]],s=starts[seat];const count=seat?1:(st.gun===1?3:1);for(let q=0;q<count;q++){const off=(q-(count-1)/2)*28;st.shots.push({x:s[0],y:s[1],tx:x+off,ty:y+off*.25,t:0,c:seat?st.players[seat][2]:g.color,w:st.gun===2?7:3})}if(target){const dmg=(seat?bet()*.5:bet()*g.damage)*(st.gun===1?2.2:1)*(1+Math.random()*.25);hit(target,dmg,seat);if(!seat&&st.gun===1){st.fish.filter(f=>f!==target&&Math.hypot(f.x-target.x,f.y-target.y)<150).slice(0,2).forEach(f=>hit(f,dmg*.45,seat))}if(!seat&&st.gun===2){st.fish.filter(f=>Math.abs(f.y-target.y)<70).slice(0,4).forEach(f=>{if(f!==target)hit(f,dmg*.35,seat)})}}}
function hit(f,dmg,seat){f.hp-=dmg;st.fx.push({x:f.x,y:f.y,t:0,c:seat?st.players[seat][2]:gun().color});if(!seat){st.run.hits++;st.combo++;st.fever=Math.min(100,st.fever+.9);if(st.fever>=100&&Date.now()>st.feverUntil){st.fever=0;st.feverUntil=Date.now()+9000;banner('OCEAN FEVER · REWARD ×2')}}if(f.hp<=0)kill(f,seat)}
function kill(f,seat){const reward=Math.round((seat?100:bet())*f.mult*ROOMS[st.room].reward*(Date.now()<st.feverUntil?2:1));st.players[seat][1]+=reward;if(!seat){P.credits+=reward;st.run.kills++;st.run.score+=reward;st.mission[0]++;st.labels.push({x:f.x,y:f.y,t:0,text:'+'+reward.toLocaleString()});save()}if(f.boss){st.mission[1]++;banner((seat?'Player '+(seat+1):'YOU')+' defeated '+f.name+' · +'+reward.toLocaleString());st.boss=null;st.bossClock=34}else if(f.hard){st.mission[2]++;emitFeed((seat?'P'+(seat+1):'YOU')+' took down '+f.name+' ×'+f.mult)}st.fish=st.fish.filter(x=>x!==f)}
function power(type){if(type==='freeze'){st.freezeUntil=Date.now()+5000;banner('DEEP FREEZE')}if(type==='lightning'){st.fish.slice(0,8).forEach(f=>hit(f,bet()*3.2,0));banner('LIGHTNING CHAIN')}if(type==='bomb'){st.fish.slice().forEach(f=>hit(f,Math.max(20,f.max*.2),0));banner('DEPTH BOMB')}if(type==='nuke'){st.fish.filter(f=>!f.boss).slice(0,12).forEach(f=>hit(f,f.max+1,0));banner('TORNADO CLEAR')}}window.power=power;
function banner(t){const b=$('#battleMsg');if(!b)return;b.textContent=t;b.classList.add('on');clearTimeout(b._t);b._t=setTimeout(()=>b.classList.remove('on'),1900)}
function emitFeed(t){const f=$('#liveFeed');if(f)f.innerHTML=`<div class="live-row"><span>${t}</span><em>LIVE</em></div>`+f.innerHTML.slice(0,1100)}
function draw(now){const c=$('#battleCanvas'),x=c.getContext('2d'),w=c.width,h=c.height;x.clearRect(0,0,w,h);const g=GAMES[st.game],gr=x.createLinearGradient(0,0,0,h);gr.addColorStop(0,'#063b5b66');gr.addColorStop(.5,g[3]+'22');gr.addColorStop(1,'#01060bb8');x.fillStyle=gr;x.fillRect(0,0,w,h);if(!LOW){for(let i=0;i<20;i++){x.fillStyle=i%2?g[3]+'55':g[4]+'44';x.beginPath();x.arc((i*93+now*.018)%w,50+(i*127)%590,2+i%4,0,7);x.fill()}}for(const f of st.fish){x.save();x.translate(f.x,f.y+Math.sin(f.phase)*4);if(f.vx>0)x.scale(-1,1);x.shadowBlur=LOW?0:(f.boss?30:f.hard?18:10);x.shadowColor=f.boss?'#ff2b3d':f.hard?'#ffd04f':g[3];x.font=`${f.r*(f.boss?1.4:1.45)}px serif`;x.textAlign='center';x.fillText(f.icon,0,f.r*.5);x.restore();x.textAlign='center';x.font=`900 ${f.boss?25:15}px system-ui`;x.strokeStyle='#02070d';x.lineWidth=4;x.strokeText('×'+f.mult,f.x,f.y+f.r*.85);x.fillStyle='#ffd353';x.fillText('×'+f.mult,f.x,f.y+f.r*.85);if(f.boss||f.lifeBar){const bw=f.boss?170:Math.max(82,Math.min(126,f.r*1.75)),bh=f.boss?9:7,bx=f.x-bw/2,by=f.y-f.r*.9;x.fillStyle='#02070de6';x.fillRect(bx-2,by-2,bw+4,bh+4);x.fillStyle=f.boss?'#ff3048':'#ffb52f';x.fillRect(bx,by,bw*Math.max(0,f.hp/f.max),bh);x.strokeStyle=f.boss?'#ff8062':'#ffe17a';x.lineWidth=1;x.strokeRect(bx,by,bw,bh)}}for(const s of st.shots){x.save();x.globalAlpha=Math.max(0,1-s.t*2);x.strokeStyle=s.c;x.lineWidth=s.w;x.shadowBlur=LOW?0:14;x.shadowColor=s.c;x.beginPath();x.moveTo(s.x,s.y);x.lineTo(s.tx,s.ty);x.stroke();x.restore()}for(const f of st.fx){x.globalAlpha=Math.max(0,1-f.t*2);x.strokeStyle=f.c;x.lineWidth=3;x.beginPath();x.arc(f.x,f.y,10+f.t*55,0,7);x.stroke()}x.globalAlpha=1;for(const l of st.labels){x.globalAlpha=Math.max(0,1-l.t*1.2);x.fillStyle='#ffd34d';x.font='900 23px system-ui';x.textAlign='center';x.fillText(l.text,l.x,l.y-l.t*42)}x.globalAlpha=1;if(st.lock&&st.fish.length){const f=bestTarget();x.strokeStyle='#ff3a40';x.lineWidth=3;x.setLineDash([8,7]);x.beginPath();x.arc(f.x,f.y,f.r*1.4,0,7);x.stroke();x.setLineDash([]);x.fillStyle='#ff6a58';x.font='900 11px system-ui';x.fillText('LOCK ON',f.x,f.y+6)}}
function hud(){if(!st.run)return;$('#bossHP').style.width=(st.boss?Math.max(0,st.boss.hp/st.boss.max*100):0)+'%';$('#bossText').textContent=st.boss?Math.max(0,Math.floor(st.boss.hp)).toLocaleString()+' / '+st.boss.max.toLocaleString():'INCOMING';$('#timeLeft').textContent='0'+Math.floor(st.waveClock/60)+':'+String(Math.floor(st.waveClock%60)).padStart(2,'0');$('#combo').textContent=st.combo;$('#fever').style.width=st.fever+'%';$('#feverPct').textContent=Math.floor(st.fever)+'%';$('#mCatch').textContent=st.mission[0]+'/50';$('#mBoss').textContent=st.mission[1]+'/3';$('#mChest').textContent=st.mission[2]+'/5';$('#radar').querySelectorAll('.dot').forEach(d=>d.remove());st.fish.slice(0,LOW?10:24).forEach(f=>{const d=document.createElement('i');d.className='dot';d.style.left=(8+84*f.x/1280)+'%';d.style.top=(8+84*f.y/720)+'%';d.style.background=f.boss?'#ff3144':f.hard?'#ffd24e':'#33dcff';$('#radar').appendChild(d)});$$('.seatgun').forEach((e,i)=>{const b=e.querySelector('.bal');if(b)b.textContent=Math.floor(st.players[i]?.[1]||0).toLocaleString()})}
function loop(n){if(!$('#game').classList.contains('on'))return;const dt=Math.min(.05,(n-st.last)/1000||.016);st.last=n;st.spawn+=dt;st.ai+=dt;st.waveClock-=dt;st.bossClock-=dt;const slow=Date.now()<st.freezeUntil?.15:1;st.fish.forEach(f=>{f.phase+=dt*2;f.x+=f.vx*dt*slow;f.y+=f.vy*dt*slow});st.fish=st.fish.filter(f=>f.x>-220&&f.x<1500&&f.y>-120&&f.y<840);if(st.spawn>Math.max(.3,.78/ROOMS[st.room].density)){st.spawn=0;if(st.fish.length<(LOW?16:42))spawn()}if(st.bossClock<=0&&!st.boss)spawn(true);if(st.waveClock<=0){st.wave++;st.waveClock=90;banner('WAVE '+st.wave+' · '+GAMES[st.game][1])}if(st.ai>.62){st.ai=0;for(let s=1;s<ROOMS[st.room].seats;s++){const f=st.fish[Math.random()*st.fish.length|0];if(f)shoot(f.x,f.y,s)}}if(st.auto&&st.fish.length&&n-st.lastShot>gun().rate){const f=bestTarget();shoot(f.x,f.y,0)}if(st.combo&&Math.random()<dt*.18)st.combo--;st.shots.forEach(s=>s.t+=dt);st.shots=st.shots.filter(s=>s.t<.55);st.fx.forEach(f=>f.t+=dt);st.fx=st.fx.filter(f=>f.t<.5);st.labels.forEach(l=>l.t+=dt);st.labels=st.labels.filter(l=>l.t<.9);draw(n);hud();st.raf=requestAnimationFrame(loop)}
function bindGame(){const c=$('#battleCanvas');const point=e=>{const r=c.getBoundingClientRect();st.pointer.x=(e.clientX-r.left)*1280/r.width;st.pointer.y=(e.clientY-r.top)*720/r.height};c.onpointermove=point;c.onpointerdown=e=>{point(e);shoot(st.pointer.x,st.pointer.y,0);clearInterval(st.hold);st.hold=setInterval(()=>shoot(st.pointer.x,st.pointer.y,0),LOW?260:130)};['pointerup','pointerleave','pointercancel'].forEach(k=>c.addEventListener(k,()=>clearInterval(st.hold)));$('#autoBtn').onclick=()=>{st.auto=!st.auto;$('#autoBtn').textContent=st.auto?'AUTO ON':'AUTO FIRE'};$('#lockBtn').onclick=()=>{st.lock=!st.lock;$('#lockBtn').textContent=st.lock?'LOCKED':'LOCK ON'};$('#leftToggle').onclick=()=>$('#leftHud').classList.toggle('open');$('#rightToggle').onclick=()=>$('#rightHud').classList.toggle('open')}
function openSlot(i){st.slot=i;$('#slotModal').classList.add('on');$('#slotTitle').textContent=SLOTS[i];$('#slotBet').textContent=st.slotBet;spin(false)}window.openSlot=openSlot;window.closeSlot=()=>$('#slotModal').classList.remove('on');window.slotBet=d=>{st.slotBet=Math.max(10,Math.min(5000,st.slotBet+(d>0?50:-50)));$('#slotBet').textContent=st.slotBet};
function spin(pay=true){if(pay){if(P.credits<st.slotBet)return;P.credits-=st.slotBet}const icons=['🔱','💎','🐚','🪸','🐬','👑','⭐','7'];const vals=[];$$('.reel').forEach(r=>{const v=icons[Math.random()*icons.length|0];r.textContent=v;vals.push(v)});let win=0;if(vals.filter(v=>v===vals[0]).length>=3)win=st.slotBet*5;if(vals[0]==='7'&&vals[1]==='7')win=st.slotBet*10;if(win){P.credits+=win;$('#slotResult').textContent='WIN +'+win.toLocaleString()}else $('#slotResult').textContent=pay?'Spin again.':'Ready.';save()}window.spin=()=>spin(true);
function init(){lobby();bindGame();$$('[data-scroll]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'}));setInterval(()=>{const e=$('#eventTimer');if(e){const s=Math.floor(Date.now()/1000)%86400,r=86400-s;e.textContent=String(Math.floor(r/3600)).padStart(2,'0')+':'+String(Math.floor((r%3600)/60)).padStart(2,'0')+':'+String(r%60).padStart(2,'0')}},1000)}init();
})();