-- F.S.A. -> EGM4000 telemetry bridge v1
-- Purpose: append-only, non-financial gameplay observations for coaching/analytics.
-- This migration intentionally does not grant any telemetry path authority over
-- player balance, game access, wallet state, or gameplay outcomes.

create table if not exists public.fsa_telemetry_sessions (
  id uuid primary key default gen_random_uuid(),
  player_id uuid not null references public.fsa_players(id) on delete restrict,
  client_kind text not null default 'web' check (client_kind in ('web','pwa','android','unknown')),
  build text not null default 'fsa-telemetry-v1' check (char_length(build) between 1 and 80),
  low_data boolean not null default false,
  started_at timestamptz not null default now(),
  last_event_at timestamptz not null default now(),
  ended_at timestamptz,
  event_count integer not null default 0 check (event_count >= 0),
  last_game_id text references public.fsa_games(id) on delete restrict,
  last_room smallint check (last_room between 0 and 2),
  constraint fsa_telemetry_sessions_end_after_start check (ended_at is null or ended_at >= started_at)
);

create table if not exists public.fsa_telemetry_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.fsa_telemetry_sessions(id) on delete restrict,
  player_id uuid not null references public.fsa_players(id) on delete restrict,
  event_type text not null check (event_type in (
    'session_start','session_end','game_open','game_close','room_change','weapon_change',
    'power_used','performance_sample','slot_open','slot_close','slot_spin','client_error'
  )),
  game_id text references public.fsa_games(id) on delete restrict,
  room smallint check (room between 0 and 2),
  payload jsonb not null default '{}'::jsonb,
  client_nonce uuid unique,
  occurred_at timestamptz not null default now(),
  source text not null default 'client_observed' check (source in ('client_observed','server_observed')),
  constraint fsa_telemetry_events_payload_object check (jsonb_typeof(payload) = 'object'),
  constraint fsa_telemetry_events_payload_size check (pg_column_size(payload) <= 4096)
);

create index if not exists fsa_telemetry_sessions_player_started_idx
  on public.fsa_telemetry_sessions(player_id, started_at desc);
create index if not exists fsa_telemetry_sessions_open_idx
  on public.fsa_telemetry_sessions(player_id, started_at desc)
  where ended_at is null;
create index if not exists fsa_telemetry_events_session_id_idx
  on public.fsa_telemetry_events(session_id, id);
create index if not exists fsa_telemetry_events_player_time_idx
  on public.fsa_telemetry_events(player_id, occurred_at desc);
create index if not exists fsa_telemetry_events_type_time_idx
  on public.fsa_telemetry_events(event_type, occurred_at desc);

alter table public.fsa_telemetry_sessions enable row level security;
alter table public.fsa_telemetry_events enable row level security;

-- Telemetry is RPC-only for players. Even authenticated clients cannot directly
-- insert/update/delete/select these tables through PostgREST.
revoke all on table public.fsa_telemetry_sessions from anon, authenticated;
revoke all on table public.fsa_telemetry_events from anon, authenticated;
revoke all on sequence public.fsa_telemetry_events_id_seq from anon, authenticated;

create or replace function fsa_private.telemetry_payload_allowed(p_payload jsonb)
returns boolean
language plpgsql
immutable
security definer
set search_path = pg_catalog, public
as $$
declare
  k text;
begin
  if p_payload is null or jsonb_typeof(p_payload) <> 'object' or pg_column_size(p_payload) > 4096 then
    return false;
  end if;

  for k in select jsonb_object_keys(p_payload)
  loop
    if k not in (
      'client','build','low_data','source','reason','shots','hits','kills','score',
      'combo','fever','gun','power','slot_id','result_class','duration_ms',
      'target_count','wave','boss_ratio'
    ) then
      return false;
    end if;
  end loop;

  return true;
end
$$;

create or replace function public.fsa_rpc_telemetry_start(
  p_client_kind text default 'web',
  p_low_data boolean default false,
  p_build text default 'fsa-telemetry-v1'
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  pid uuid;
  sid uuid;
  kind text := lower(coalesce(nullif(trim(p_client_kind),''),'unknown'));
  build_name text := coalesce(nullif(trim(p_build),''),'fsa-telemetry-v1');
begin
  pid := fsa_private.session_player_id();
  if pid is null then raise exception 'FSA_PLAYER_AUTH_REQUIRED'; end if;
  if kind not in ('web','pwa','android','unknown') then kind := 'unknown'; end if;
  if char_length(build_name) > 80 then raise exception 'FSA_TELEMETRY_BUILD_INVALID'; end if;

  insert into public.fsa_telemetry_sessions(player_id,client_kind,build,low_data)
  values(pid,kind,build_name,coalesce(p_low_data,false))
  returning id into sid;

  insert into public.fsa_telemetry_events(session_id,player_id,event_type,payload,source)
  values(
    sid,
    pid,
    'session_start',
    jsonb_build_object('client',kind,'build',build_name,'low_data',coalesce(p_low_data,false),'source','fsa'),
    'server_observed'
  );

  update public.fsa_telemetry_sessions
  set event_count=1,last_event_at=now()
  where id=sid;

  return sid;
end
$$;

create or replace function public.fsa_rpc_telemetry_event(
  p_session_id uuid,
  p_event_type text,
  p_game_id text default null,
  p_room smallint default null,
  p_payload jsonb default '{}'::jsonb,
  p_client_nonce uuid default null
)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  pid uuid;
  eid bigint;
  et text := lower(coalesce(trim(p_event_type),''));
begin
  pid := fsa_private.session_player_id();
  if pid is null then raise exception 'FSA_PLAYER_AUTH_REQUIRED'; end if;

  if et not in (
    'game_open','game_close','room_change','weapon_change','power_used',
    'performance_sample','slot_open','slot_close','slot_spin','client_error'
  ) then
    raise exception 'FSA_TELEMETRY_EVENT_INVALID';
  end if;

  if p_room is not null and (p_room < 0 or p_room > 2) then
    raise exception 'FSA_TELEMETRY_ROOM_INVALID';
  end if;

  if not fsa_private.telemetry_payload_allowed(coalesce(p_payload,'{}'::jsonb)) then
    raise exception 'FSA_TELEMETRY_PAYLOAD_INVALID';
  end if;

  perform 1
  from public.fsa_telemetry_sessions s
  where s.id=p_session_id and s.player_id=pid and s.ended_at is null;
  if not found then raise exception 'FSA_TELEMETRY_SESSION_INVALID'; end if;

  if p_game_id is not null then
    perform 1
    from public.fsa_games g
    join public.fsa_player_game_access a on a.game_id=g.id and a.player_id=pid
    where g.id=p_game_id and g.active;
    if not found then raise exception 'FSA_GAME_ACCESS_DENIED'; end if;
  end if;

  if p_client_nonce is not null then
    select e.id into eid
    from public.fsa_telemetry_events e
    where e.client_nonce=p_client_nonce and e.player_id=pid;
    if eid is not null then return eid; end if;
  end if;

  insert into public.fsa_telemetry_events(
    session_id,player_id,event_type,game_id,room,payload,client_nonce,source
  ) values(
    p_session_id,pid,et,p_game_id,p_room,coalesce(p_payload,'{}'::jsonb),p_client_nonce,'client_observed'
  )
  returning id into eid;

  update public.fsa_telemetry_sessions
  set event_count=event_count+1,
      last_event_at=now(),
      last_game_id=coalesce(p_game_id,last_game_id),
      last_room=coalesce(p_room,last_room)
  where id=p_session_id and player_id=pid;

  return eid;
end
$$;

create or replace function public.fsa_rpc_telemetry_end(
  p_session_id uuid,
  p_payload jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  pid uuid;
begin
  pid := fsa_private.session_player_id();
  if pid is null then raise exception 'FSA_PLAYER_AUTH_REQUIRED'; end if;
  if not fsa_private.telemetry_payload_allowed(coalesce(p_payload,'{}'::jsonb)) then
    raise exception 'FSA_TELEMETRY_PAYLOAD_INVALID';
  end if;

  perform 1
  from public.fsa_telemetry_sessions s
  where s.id=p_session_id and s.player_id=pid and s.ended_at is null
  for update;
  if not found then return; end if;

  insert into public.fsa_telemetry_events(session_id,player_id,event_type,payload,source)
  values(p_session_id,pid,'session_end',coalesce(p_payload,'{}'::jsonb),'server_observed');

  update public.fsa_telemetry_sessions
  set ended_at=now(),last_event_at=now(),event_count=event_count+1
  where id=p_session_id and player_id=pid;
end
$$;

-- Founder/AAL2-only sanitized feed for EGM4000 integration testing and export.
-- It deliberately omits username, email, wallet/balance and game-access data.
create or replace function public.fsa_rpc_egm4000_telemetry_feed(
  p_after_id bigint default 0,
  p_limit integer default 200
)
returns table(
  event_id bigint,
  session_id uuid,
  player_id uuid,
  event_type text,
  game_id text,
  room smallint,
  payload jsonb,
  occurred_at timestamptz,
  source text
)
language plpgsql
stable
security definer
set search_path = pg_catalog, public, auth
as $$
begin
  if coalesce(fsa_private.session_role(),'') <> 'founder'
     or coalesce(auth.jwt()->>'aal','aal1') <> 'aal2' then
    raise exception 'FSA_FOUNDER_MFA_REQUIRED';
  end if;

  return query
  select e.id,e.session_id,e.player_id,e.event_type,e.game_id,e.room,e.payload,e.occurred_at,e.source
  from public.fsa_telemetry_events e
  where e.id > greatest(coalesce(p_after_id,0),0)
  order by e.id asc
  limit least(greatest(coalesce(p_limit,200),1),1000);
end
$$;

revoke all on function fsa_private.telemetry_payload_allowed(jsonb) from public, anon, authenticated;
revoke all on function public.fsa_rpc_telemetry_start(text,boolean,text) from public, anon;
revoke all on function public.fsa_rpc_telemetry_event(uuid,text,text,smallint,jsonb,uuid) from public, anon;
revoke all on function public.fsa_rpc_telemetry_end(uuid,jsonb) from public, anon;
revoke all on function public.fsa_rpc_egm4000_telemetry_feed(bigint,integer) from public, anon;

grant execute on function public.fsa_rpc_telemetry_start(text,boolean,text) to authenticated;
grant execute on function public.fsa_rpc_telemetry_event(uuid,text,text,smallint,jsonb,uuid) to authenticated;
grant execute on function public.fsa_rpc_telemetry_end(uuid,jsonb) to authenticated;
grant execute on function public.fsa_rpc_egm4000_telemetry_feed(bigint,integer) to authenticated;

comment on table public.fsa_telemetry_sessions is 'F.S.A. authenticated gameplay telemetry sessions for analytics/coaching. No wallet authority.';
comment on table public.fsa_telemetry_events is 'Append-only F.S.A. non-financial gameplay observations for EGM4000 analytics/coaching.';
comment on function public.fsa_rpc_egm4000_telemetry_feed(bigint,integer) is 'Founder MFA-only sanitized F.S.A. telemetry feed for EGM4000 integration.';
