import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4'

const SUPABASE_URL='https://nqcshihyfhthywpseilx.supabase.co'
const SUPABASE_KEY='sb_publishable_lD--sdVpwV9djLF28XW1Jg_95DPa58G'
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:'pkce'}})
const $=s=>document.querySelector(s)
const $$=s=>[...document.querySelectorAll(s)]
const LEGACY_KEYS=['fsa.founder.console.v2','fsa.founder.console.v1']

const S={session:null,profile:null,mfaReady:false,aal:null,factors:[],enrollFactor:null,games:[],agents:[],players:[],agentGames:[],playerGames:[],ledger:[],audit:[],meta:null}
let toastTimer=null
let modalAction=null

function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function fmt(n){return Number(n||0).toLocaleString()}
function notify(message,danger=false){const t=$('#toast');t.textContent=message;t.className=`toast on${danger?' danger':''}`;clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.className='toast',3000)}
function friendly(error){const raw=String(error?.message||error?.error_description||error?.error||error||'Unknown error');const map={FSA_MFA_REQUIRED:'MFA verification is required for this action.',FSA_FOUNDER_REQUIRED:'Founder authority is required.',FSA_CASHIER_REQUIRED:'This Agent does not have cashier authority.',FSA_MODERATOR_REQUIRED:'This Agent does not have moderator authority.',FSA_OPERATOR_INACTIVE:'This operator account is suspended.',FSA_AGENT_INACTIVE:'This Agent is suspended.',FSA_PLAYER_SUSPENDED:'This user is suspended.',FSA_SCOPE_DENIED:'That record is outside this Agent scope.',FSA_CREDIT_CEILING_EXCEEDED:'The Agent credit ceiling would be exceeded.',FSA_NEGATIVE_BALANCE:'That adjustment would make the balance negative.',FSA_USERNAME_TAKEN:'That username is already in use.',FSA_ALREADY_REVERSED:'That ledger entry has already been reversed.',FSA_REVERSAL_OF_REVERSAL_DENIED:'Reversal entries cannot themselves be reversed.',FSA_CEILING_BELOW_CURRENT_EXPOSURE:'The new ceiling is below the Agent’s current user balances.'};return map[raw]||raw.replace(/^Error:\s*/,'')}
function isFounder(){return S.profile?.role==='founder'}
function currentAgent(){return S.agents.find(a=>a.id===S.profile?.agent_id)||null}
function canCashier(){return isFounder()||!!currentAgent()?.can_cashier}
function canModerate(){return isFounder()||!!currentAgent()?.can_moderate}
function canMutate(){return !!S.mfaReady&&S.profile?.status==='active'}
function agentName(id){return S.agents.find(a=>a.id===id)?.display_name||S.agents.find(a=>a.id===id)?.username||'Unassigned'}
function gameName(id){return S.games.find(g=>g.id===id)?.name||id}
function agentGameIds(id){return S.agentGames.filter(x=>x.agent_id===id).map(x=>x.game_id)}
function playerGameIds(id){return S.playerGames.filter(x=>x.player_id===id).map(x=>x.game_id)}
function requireMfa(){if(S.mfaReady)return true;renderSecurity();$('#securityDialog').showModal();notify('Verify MFA before making administrative changes.',true);return false}
function setGate(name){$('#authGate').classList.toggle('hidden',name!=='auth');$('#recoveryGate').classList.toggle('hidden',name!=='recovery');$('#consoleShell').classList.toggle('hidden',name!=='console')}

async function loadProfile(){const {data,error}=await supabase.from('fsa_operator_profiles').select('*').eq('user_id',S.session.user.id).maybeSingle();if(error)throw error;if(!data)throw new Error('This authenticated account is not an F.S.A. Founder Console operator.');if(data.status!=='active')throw new Error('This F.S.A. operator account is suspended.');S.profile=data}

async function refreshMfa(){const [{data:aal,error:aalError},{data:factors,error:factorError}]=await Promise.all([supabase.auth.mfa.getAuthenticatorAssuranceLevel(),supabase.auth.mfa.listFactors()]);if(aalError)throw aalError;if(factorError)throw factorError;S.aal=aal;S.factors=[...(factors?.totp||[]),...(factors?.phone||[])].filter(f=>f.status==='verified');S.mfaReady=aal?.currentLevel==='aal2';renderSecurity()}

async function loadData(){const queries=[
  supabase.from('fsa_backend_meta').select('*').maybeSingle(),
  supabase.from('fsa_games').select('*').eq('active',true).order('category').order('name'),
  supabase.from('fsa_agents').select('*').order('display_name'),
  supabase.from('fsa_players').select('*').order('created_at',{ascending:false}),
  supabase.from('fsa_agent_game_access').select('*'),
  supabase.from('fsa_player_game_access').select('*'),
  supabase.from('fsa_credit_ledger').select('*').order('created_at',{ascending:false}).limit(500),
  supabase.from('fsa_audit_log').select('*').order('created_at',{ascending:false}).limit(500)
];const results=await Promise.all(queries);for(const r of results)if(r.error)throw r.error;[S.meta,S.games,S.agents,S.players,S.agentGames,S.playerGames,S.ledger,S.audit]=results.map(r=>r.data);render()}

async function handleSession(session){S.session=session;if(!session){S.profile=null;setGate('auth');return}try{await loadProfile();setGate('console');$('#operatorEmail').textContent=session.user.email||'';await refreshMfa();await loadData()}catch(e){setGate('auth');$('#authMessage').textContent=friendly(e);await supabase.auth.signOut().catch(()=>{});notify(friendly(e),true)}}

function renderSecurity(){if(!S.profile)return;const verified=S.factors.length;$('#operatorBadge').textContent=`${S.profile.role.toUpperCase()} · ${S.mfaReady?'MFA VERIFIED':'READ ONLY'}`;$('#operatorBadge').className=`pill ${S.mfaReady?'ok':'danger'}`;$('#securityBanner').innerHTML=S.mfaReady?'<b>Secure session:</b> MFA/AAL2 verified. Administrative mutations are unlocked.':'<b>Read-only session:</b> sign-in succeeded, but the database will reject administrative mutations until MFA/AAL2 is verified.';$('#aalStatus').textContent=`Current assurance: ${S.aal?.currentLevel||'aal1'} · verified factors: ${verified}`;$('#mfaExisting').classList.toggle('hidden',verified===0||S.mfaReady);$('#mfaEnroll').classList.toggle('hidden',verified>0||S.mfaReady);$$('[data-mutation]').forEach(el=>el.disabled=!S.mfaReady)}

function render(){if(!S.profile)return;const meAgent=currentAgent();$('#scopeNote').innerHTML=isFounder()?'<b>Founder scope:</b> server-authorized access to all F.S.A. Agents, users, credits, permissions and audit records.':`<b>Agent scope:</b> ${esc(meAgent?.display_name||'Agent')} · ${meAgent?.can_cashier?'cashier enabled':'cashier disabled'} · ${meAgent?.can_moderate?'moderator enabled':'moderator disabled'} · RLS hides all other Agents’ records.`;const users=S.players,totalCredits=users.reduce((n,u)=>n+Number(u.balance||0),0);$('#stats').innerHTML=[["Visible users",users.length],[isFounder()?"Agents":"My Agent",S.agents.length],["Virtual credits",fmt(totalCredits)],["Active games",S.games.length]].map(([a,b])=>`<div class="card"><span>${a}</span><strong>${b}</strong></div>`).join('');const low=users.filter(u=>u.status==='active'&&Number(u.balance)<250).slice(0,12);$('#lowBalances').innerHTML=low.length?low.map(u=>`<span class="pill danger">${esc(u.display_name||u.username)} · ${fmt(u.balance)}</span>`).join(' '):'<span class="ok">No visible users below 250 credits.</span>';$('#quAgent').innerHTML=S.agents.map(a=>`<option value="${a.id}">${esc(a.display_name)}</option>`).join('');$('#quAgent').disabled=!isFounder();if(!isFounder()&&S.profile.agent_id)$('#quAgent').value=S.profile.agent_id;$('#qcUser').innerHTML=users.map(u=>`<option value="${u.id}">${esc(u.display_name||u.username)} (${fmt(u.balance)})</option>`).join('');if(!canCashier()&&!isFounder()){$('#quCredits').value='0'}$('#quickCreditSubmit').disabled=!canMutate()||!canCashier()||!users.length;$('#quickUserSubmit').disabled=!canMutate();$('#addUser').disabled=!canMutate();$('#addAgent').disabled=!canMutate()||!isFounder();document.querySelector('[data-tab="agents"]').disabled=!isFounder()&&S.agents.length===0;const legacy=LEGACY_KEYS.some(k=>localStorage.getItem(k));$('#legacyBackup').classList.toggle('hidden',!legacy);renderUsers();renderAgents();renderLedger();renderGames();renderAudit();renderSecurity()}

function renderUsers(){const q=$('#userSearch').value.trim().toLowerCase();const rows=S.players.filter(u=>`${u.username} ${u.display_name} ${agentName(u.agent_id)} ${u.notes}`.toLowerCase().includes(q)).map(u=>{const gameCount=playerGameIds(u.id).length;const allowed=agentGameIds(u.agent_id).length;return `<tr><td><b>${esc(u.display_name||u.username)}</b><br><small>${esc(u.username)}</small></td><td>${esc(agentName(u.agent_id))}</td><td><span class="pill ${u.status==='active'?'ok':'danger'}">${u.status}</span></td><td class="money">${fmt(u.balance)}</td><td>${gameCount}/${allowed}</td><td class="actions"><button data-action="credit" data-id="${u.id}" ${!canMutate()||!canCashier()?'disabled':''}>Adjust credits</button><button data-action="edit-user" data-id="${u.id}" ${!canMutate()||!canModerate()?'disabled':''}>Edit</button><button data-action="toggle-user" data-id="${u.id}" ${!canMutate()||!canModerate()?'disabled':''}>${u.status==='active'?'Suspend':'Reactivate'}</button></td></tr>`}).join('');$('#usersTable').innerHTML=`<div class="table"><table><thead><tr><th>User</th><th>Agent</th><th>Status</th><th>Credits</th><th>Games</th><th>Actions</th></tr></thead><tbody>${rows||'<tr><td colspan="6">No users in this server-authorized scope.</td></tr>'}</tbody></table></div>`}

function renderAgents(){if(!isFounder()){const a=currentAgent();$('#agentsTable').innerHTML=a?`<article><h3>${esc(a.display_name)}</h3><p><b>Status:</b> ${esc(a.status)} · <b>Credit ceiling:</b> ${fmt(a.credit_ceiling)} · <b>Cashier:</b> ${a.can_cashier?'Yes':'No'} · <b>Moderator:</b> ${a.can_moderate?'Yes':'No'}</p></article>`:'<p>No Agent record is attached to this account.</p>';return}const rows=S.agents.map(a=>{const users=S.players.filter(u=>u.agent_id===a.id),credits=users.reduce((n,u)=>n+Number(u.balance||0),0);return `<tr><td><b>${esc(a.display_name)}</b><br><small>${esc(a.username)}</small></td><td><span class="pill ${a.status==='active'?'ok':'danger'}">${a.status}</span></td><td>${users.length}</td><td class="money">${fmt(credits)}</td><td>${fmt(a.credit_ceiling)}</td><td>${a.can_cashier?'Yes':'No'}</td><td>${a.can_moderate?'Yes':'No'}</td><td class="actions"><button data-action="edit-agent" data-id="${a.id}" ${!canMutate()?'disabled':''}>Edit</button><button data-action="toggle-agent" data-id="${a.id}" ${!canMutate()?'disabled':''}>${a.status==='active'?'Suspend':'Reactivate'}</button></td></tr>`}).join('');$('#agentsTable').innerHTML=`<div class="table"><table><thead><tr><th>Agent</th><th>Status</th><th>Users</th><th>User balances</th><th>Ceiling</th><th>Cashier</th><th>Moderator</th><th>Actions</th></tr></thead><tbody>${rows||'<tr><td colspan="8">No Agents yet.</td></tr>'}</tbody></table></div>`}

function renderLedger(){const q=$('#ledgerSearch').value.trim().toLowerCase();const rows=S.ledger.filter(l=>{const u=S.players.find(x=>x.id===l.player_id);return `${l.reason} ${u?.username||''} ${u?.display_name||''}`.toLowerCase().includes(q)}).map(l=>{const u=S.players.find(x=>x.id===l.player_id);const reversed=S.ledger.some(x=>x.reverses_entry_id===l.id);const action=l.kind==='reversal'?'Reversal':reversed?'Reversed':`<button data-action="reverse" data-id="${l.id}" ${!canMutate()||!canCashier()?'disabled':''}>Reverse</button>`;return `<tr><td>${new Date(l.created_at).toLocaleString()}</td><td>${esc(u?.display_name||u?.username||l.player_id)}</td><td class="${Number(l.amount)>=0?'ok':'danger'}">${Number(l.amount)>=0?'+':''}${fmt(l.amount)}</td><td>${fmt(l.balance_after)}</td><td>${esc(l.reason)}</td><td>${esc(l.kind)}</td><td>${action}</td></tr>`}).join('');$('#ledgerTable').innerHTML=`<div class="table"><table><thead><tr><th>Time</th><th>User</th><th>Change</th><th>Balance</th><th>Reason</th><th>Kind</th><th>Correction</th></tr></thead><tbody>${rows||'<tr><td colspan="7">No ledger entries.</td></tr>'}</tbody></table></div>`}

function renderGames(){const agentCards=S.agents.map(a=>{const allowed=new Set(agentGameIds(a.id));return `<article data-agent-card="${a.id}"><h3>${esc(a.display_name)} <small>${allowed.size}/${S.games.length} allowed</small></h3><div class="games">${S.games.map(g=>`<label class="game"><input type="checkbox" data-agent-game="${a.id}" value="${g.id}" ${allowed.has(g.id)?'checked':''} ${!isFounder()||!canMutate()?'disabled':''}><span>${esc(g.name)}</span></label>`).join('')}</div></article>`}).join('');const userCards=S.players.map(u=>{const allowed=new Set(agentGameIds(u.agent_id)),on=new Set(playerGameIds(u.id));return `<article class="access-group" data-player-card="${u.id}"><h4><span>${esc(u.display_name||u.username)}</span><small>${on.size}/${allowed.size} enabled</small></h4><div class="games">${S.games.map(g=>{const inherited=allowed.has(g.id);return `<label class="game ${inherited?'':'inherited-off'}"><input type="checkbox" data-player-game="${u.id}" value="${g.id}" ${on.has(g.id)?'checked':''} ${!inherited||!canMutate()||!canModerate()?'disabled':''}><span>${esc(g.name)}</span>${!inherited?'<small>Agent blocked</small>':''}</label>`}).join('')}</div></article>`}).join('');$('#gamesPanel').innerHTML=agentCards+userCards||'<p>No game-access records.</p>'}

function renderAudit(){const rows=S.audit.map(x=>`<tr><td>${new Date(x.created_at).toLocaleString()}</td><td>${esc(x.actor_role)}</td><td>${esc(x.action)}</td><td>${esc(x.target_type)}</td><td><code>${esc(x.target_id||'')}</code></td><td><small>${esc(JSON.stringify(x.details||{}))}</small></td></tr>`).join('');$('#auditTable').innerHTML=`<div class="table"><table><thead><tr><th>Time</th><th>Actor role</th><th>Action</th><th>Target</th><th>ID</th><th>Details</th></tr></thead><tbody>${rows||'<tr><td colspan="6">No audit events.</td></tr>'}</tbody></table></div>`}

async function callRpc(name,args){if(!requireMfa())throw new Error('FSA_MFA_REQUIRED');const {data,error}=await supabase.rpc(name,args);if(error)throw error;await loadData();return data}
function openModal(title,html,onSave){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;modalAction=onSave;$('#modal').showModal()}
function closeModal(){modalAction=null;$('#modal').close()}

function openCreateUser(){if(!requireMfa())return;const options=S.agents.map(a=>`<option value="${a.id}">${esc(a.display_name)}</option>`).join('');openModal('Create user',`<label>Username<input name="username" maxlength="60" required></label><label>Display name<input name="display" maxlength="80"></label><label>Agent<select name="agent" ${isFounder()?'':'disabled'}>${options}</select></label><label>Opening virtual credits<input name="credits" type="number" min="0" step="1" value="${canCashier()?1000:0}"></label><label>Notes<textarea name="notes" maxlength="500"></textarea></label>`,async fd=>{const agent=isFounder()?fd.get('agent'):S.profile.agent_id;await callRpc('fsa_rpc_create_player',{p_username:String(fd.get('username')),p_display_name:String(fd.get('display')||''),p_agent_id:agent,p_opening_balance:Number(fd.get('credits')||0),p_game_ids:null,p_notes:String(fd.get('notes')||'')});notify('User created on the production backend.')})}

function openCredit(id){if(!requireMfa())return;const u=S.players.find(x=>x.id===id);if(!u)return;openModal(`Adjust ${u.display_name||u.username}`,`<label>Credit change<input name="delta" type="number" step="1" value="100" required></label><label>Reason<input name="reason" maxlength="250" value="Manual adjustment" required></label>`,async fd=>{await callRpc('fsa_rpc_adjust_credits',{p_player_id:id,p_delta:Number(fd.get('delta')),p_reason:String(fd.get('reason'))});notify('Credit ledger updated.')})}

function openEditUser(id){if(!requireMfa())return;const u=S.players.find(x=>x.id===id);if(!u)return;const options=S.agents.map(a=>`<option value="${a.id}" ${a.id===u.agent_id?'selected':''}>${esc(a.display_name)}</option>`).join('');openModal(`Edit ${u.display_name||u.username}`,`<label>Display name<input name="display" maxlength="80" value="${esc(u.display_name)}"></label><label>Status<select name="status"><option value="active" ${u.status==='active'?'selected':''}>active</option><option value="suspended" ${u.status==='suspended'?'selected':''}>suspended</option></select></label><label>Agent<select name="agent" ${isFounder()?'':'disabled'}>${options}</select></label><label>Notes<textarea name="notes" maxlength="500">${esc(u.notes)}</textarea></label>`,async fd=>{await callRpc('fsa_rpc_update_player',{p_player_id:id,p_display_name:String(fd.get('display')||u.display_name),p_status:String(fd.get('status')),p_agent_id:isFounder()?String(fd.get('agent')):u.agent_id,p_notes:String(fd.get('notes')||'')});notify('User updated.')})}

async function toggleUser(id){if(!requireMfa())return;const u=S.players.find(x=>x.id===id);if(!u)return;try{await callRpc('fsa_rpc_update_player',{p_player_id:id,p_display_name:u.display_name,p_status:u.status==='active'?'suspended':'active',p_agent_id:u.agent_id,p_notes:u.notes});notify(`User ${u.status==='active'?'suspended':'reactivated'}.`)}catch(e){notify(friendly(e),true)}}

function openInviteAgent(){if(!requireMfa()||!isFounder())return;openModal('Invite authenticated Agent',`<label>Email<input name="email" type="email" required></label><label>Username<input name="username" maxlength="60" required></label><label>Display name<input name="display" maxlength="80"></label><label>Credit ceiling<input name="ceiling" type="number" min="0" step="1" value="50000"></label><label class="check"><input name="cashier" type="checkbox"> Cashier authority</label><label class="check"><input name="moderator" type="checkbox"> Moderator authority</label>`,async fd=>{const {data,error}=await supabase.functions.invoke('fsa-founder-admin',{body:{action:'invite_agent',email:String(fd.get('email')),username:String(fd.get('username')),display_name:String(fd.get('display')||fd.get('username')),credit_ceiling:Number(fd.get('ceiling')||0),can_cashier:fd.get('cashier')==='on',can_moderate:fd.get('moderator')==='on',game_ids:S.games.map(g=>g.id)}});if(error)throw error;if(data?.error)throw new Error(data.error);await loadData();notify(data?.invited?'Agent invitation sent.':'Existing auth account linked as Agent.')})}

function openEditAgent(id){if(!requireMfa()||!isFounder())return;const a=S.agents.find(x=>x.id===id);if(!a)return;openModal(`Edit ${a.display_name}`,`<label>Display name<input name="display" value="${esc(a.display_name)}" maxlength="80"></label><label>Status<select name="status"><option value="active" ${a.status==='active'?'selected':''}>active</option><option value="suspended" ${a.status==='suspended'?'selected':''}>suspended</option></select></label><label>Credit ceiling<input name="ceiling" type="number" min="0" step="1" value="${a.credit_ceiling}"></label><label class="check"><input name="cashier" type="checkbox" ${a.can_cashier?'checked':''}> Cashier authority</label><label class="check"><input name="moderator" type="checkbox" ${a.can_moderate?'checked':''}> Moderator authority</label>`,async fd=>{await callRpc('fsa_rpc_update_agent',{p_agent_id:id,p_display_name:String(fd.get('display')||a.display_name),p_status:String(fd.get('status')),p_credit_ceiling:Number(fd.get('ceiling')),p_can_cashier:fd.get('cashier')==='on',p_can_moderate:fd.get('moderator')==='on'});notify('Agent updated.')})}

async function toggleAgent(id){if(!requireMfa()||!isFounder())return;const a=S.agents.find(x=>x.id===id);if(!a)return;try{await callRpc('fsa_rpc_update_agent',{p_agent_id:id,p_display_name:a.display_name,p_status:a.status==='active'?'suspended':'active',p_credit_ceiling:Number(a.credit_ceiling),p_can_cashier:a.can_cashier,p_can_moderate:a.can_moderate});notify(`Agent ${a.status==='active'?'suspended':'reactivated'}.`)}catch(e){notify(friendly(e),true)}}

async function reverseLedger(id){if(!requireMfa())return;try{await callRpc('fsa_rpc_reverse_credit',{p_ledger_id:id,p_reason:'Founder Console reversal'});notify('Compensating reversal created.') }catch(e){notify(friendly(e),true)}}

async function saveAgentGames(agentId){if(!requireMfa()||!isFounder())return;const ids=$$(`input[data-agent-game="${agentId}"]:checked`).map(x=>x.value);try{await callRpc('fsa_rpc_set_agent_games',{p_agent_id:agentId,p_game_ids:ids});notify('Agent game access updated.') }catch(e){notify(friendly(e),true);await loadData()}}
async function savePlayerGames(playerId){if(!requireMfa())return;const ids=$$(`input[data-player-game="${playerId}"]:checked`).map(x=>x.value);try{await callRpc('fsa_rpc_set_player_games',{p_player_id:playerId,p_game_ids:ids});notify('User game access updated.') }catch(e){notify(friendly(e),true);await loadData()}}

function exportServerData(){const payload={exported_at:new Date().toISOString(),profile:S.profile,meta:S.meta,agents:S.agents,players:S.players,agent_game_access:S.agentGames,player_game_access:S.playerGames,credit_ledger:S.ledger,audit_log:S.audit};downloadJson('fsa-founder-console-server-export.json',payload)}
function legacyBackup(){for(const key of LEGACY_KEYS){const raw=localStorage.getItem(key);if(raw){try{downloadJson(`fsa-legacy-browser-backup-${key.endsWith('v2')?'v2':'v1'}.json`,JSON.parse(raw));notify('Legacy browser backup downloaded. It is not production authority.');return}catch{}}}notify('No readable legacy browser data found.',true)}
function downloadJson(name,obj){const url=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}

function setupTabs(){$$('nav [data-tab]').forEach(btn=>btn.addEventListener('click',()=>{if(btn.disabled)return;$$('nav [data-tab]').forEach(x=>x.classList.toggle('active',x===btn));$$('.tab').forEach(x=>x.classList.toggle('active',x.id===btn.dataset.tab))}))}

$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#authMessage').textContent='Signing in…';const email=$('#loginEmail').value.trim(),password=$('#loginPassword').value;const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error){$('#authMessage').textContent=friendly(error);return}$('#authMessage').textContent='';await handleSession(data.session)})
$('#forgotPassword').addEventListener('click',async()=>{const email=$('#loginEmail').value.trim();if(!email){$('#authMessage').textContent='Enter your operator email first.';return}const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});$('#authMessage').textContent=error?friendly(error):'Password reset email requested. Check the account inbox.'})
$('#recoveryForm').addEventListener('submit',async e=>{e.preventDefault();const a=$('#newPassword').value,b=$('#confirmPassword').value;if(a!==b){$('#recoveryMessage').textContent='Passwords do not match.';return}const {error}=await supabase.auth.updateUser({password:a});if(error){$('#recoveryMessage').textContent=friendly(error);return}$('#recoveryMessage').textContent='Password updated. Returning to the console…';const {data}=await supabase.auth.getSession();await handleSession(data.session)})
$('#signOutButton').addEventListener('click',async()=>{await supabase.auth.signOut();setGate('auth')})
$('#securityButton').addEventListener('click',()=>{renderSecurity();$('#securityDialog').showModal()})
$('#securityClose').addEventListener('click',()=>$('#securityDialog').close())
$('#beginMfaEnroll').addEventListener('click',async()=>{try{const {data,error}=await supabase.auth.mfa.enroll({factorType:'totp',friendlyName:'FSA Founder Console'});if(error)throw error;S.enrollFactor=data;$('#mfaQr').src=data.totp.qr_code;$('#mfaSecret').textContent=data.totp.secret;$('#mfaEnrollDetails').classList.remove('hidden')}catch(e){notify(friendly(e),true)}})
$('#verifyMfaEnroll').addEventListener('click',async()=>{try{if(!S.enrollFactor)throw new Error('Start MFA enrollment first.');const code=$('#mfaEnrollCode').value.trim();const {error}=await supabase.auth.mfa.challengeAndVerify({factorId:S.enrollFactor.id,code});if(error)throw error;await supabase.auth.refreshSession();S.enrollFactor=null;await refreshMfa();await loadData();$('#securityDialog').close();notify('MFA enrolled and verified.') }catch(e){notify(friendly(e),true)}})
$('#verifyExistingMfa').addEventListener('click',async()=>{try{const factor=S.factors[0];if(!factor)throw new Error('No verified MFA factor found.');const code=$('#mfaLoginCode').value.trim();const {error}=await supabase.auth.mfa.challengeAndVerify({factorId:factor.id,code});if(error)throw error;await supabase.auth.refreshSession();await refreshMfa();await loadData();$('#securityDialog').close();notify('MFA verified. Administrative actions unlocked.') }catch(e){notify(friendly(e),true)}})

$('#quickUser').addEventListener('submit',async e=>{e.preventDefault();if(!requireMfa())return;try{await callRpc('fsa_rpc_create_player',{p_username:$('#quName').value.trim(),p_display_name:$('#quDisplay').value.trim(),p_agent_id:$('#quAgent').value,p_opening_balance:Number($('#quCredits').value||0),p_game_ids:null,p_notes:''});$('#quName').value='';$('#quDisplay').value='';notify('User created.') }catch(err){notify(friendly(err),true)}})
$('#quickCredit').addEventListener('submit',async e=>{e.preventDefault();if(!requireMfa())return;try{await callRpc('fsa_rpc_adjust_credits',{p_player_id:$('#qcUser').value,p_delta:Number($('#qcAmount').value),p_reason:$('#qcReason').value.trim()});notify('Credit adjustment recorded.') }catch(err){notify(friendly(err),true)}})
$('#addUser').addEventListener('click',openCreateUser)
$('#addAgent').addEventListener('click',openInviteAgent)
$('#exportData').addEventListener('click',exportServerData)
$('#legacyBackup').addEventListener('click',legacyBackup)
$('#userSearch').addEventListener('input',renderUsers)
$('#ledgerSearch').addEventListener('input',renderLedger)
$('#modalCancel').addEventListener('click',closeModal)
$('#modalForm').addEventListener('submit',async e=>{e.preventDefault();if(!modalAction)return;const action=modalAction;const fd=new FormData(e.currentTarget);$('#modalSave').disabled=true;try{await action(fd);closeModal()}catch(err){notify(friendly(err),true)}finally{$('#modalSave').disabled=false}})

$('main').addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(!b)return;const {action,id}=b.dataset;if(action==='credit')openCredit(id);else if(action==='edit-user')openEditUser(id);else if(action==='toggle-user')toggleUser(id);else if(action==='edit-agent')openEditAgent(id);else if(action==='toggle-agent')toggleAgent(id);else if(action==='reverse')reverseLedger(id)})
$('#gamesPanel').addEventListener('change',e=>{const el=e.target;if(el.matches('[data-agent-game]'))saveAgentGames(el.dataset.agentGame);else if(el.matches('[data-player-game]'))savePlayerGames(el.dataset.playerGame)})

supabase.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'){S.session=session;setGate('recovery');return}if(event==='SIGNED_OUT'){S.session=null;S.profile=null;setGate('auth')}})
setupTabs()
const {data:{session}}=await supabase.auth.getSession()
await handleSession(session)
