const GAMES=["Reef Run","Dragon Depths","Pirate’s Plunder","Atlantis Rising","Ice Tide","Lava Reef","Storm Seas","Jade Dragon","Neon Ocean","Ancient Ruins","Mecha Marine","Coral Chaos","Kraken’s Lair","Treasure Trials","Boss Rush","Ocean Fortune","Treasure Reels","Siren’s Gold","Legend of Atlantis","Shark Jackpot","Pearl Rush","Kraken Spins","Reef Riches","Lucky Tide","Deep Diamonds","Golden Anchor","Mermaid’s Treasure","Pirate Jackpot","Coral Cash","Neptune’s Wheel","Sea King 777","Ocean Wilds","Diamond Dolphin","Wild Pearls","Treasure Temple"];
const KEY="fsa.founder.console.v2";
const LEGACY_KEY="fsa.founder.console.v1";
const $=s=>document.querySelector(s);
let toastTimer;
let S=load();

function id(prefix){return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`}
function now(){return new Date().toISOString()}
function esc(value){return String(value??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function unique(list){return [...new Set(list)]}
function clampInt(value,min=0,max=Number.MAX_SAFE_INTEGER){const n=Math.floor(Number(value));return Number.isFinite(n)?Math.max(min,Math.min(max,n)):min}
function seed(){return {version:2,agents:[{id:"a1",name:"House Agent",status:"active",creditLimit:50000,cashier:true,moderator:false,games:[...GAMES]}],users:[{id:"u1",name:"ReefRider",agentId:"a1",status:"active",credits:12450,games:[...GAMES.slice(0,15)],notes:"Demo user"}],ledger:[],audit:[]}}
function normalize(raw){const state=raw&&typeof raw==='object'?raw:seed();state.version=2;state.agents=Array.isArray(state.agents)?state.agents:[];state.users=Array.isArray(state.users)?state.users:[];state.ledger=Array.isArray(state.ledger)?state.ledger:[];state.audit=Array.isArray(state.audit)?state.audit:[];state.agents.forEach((a,i)=>{a.id=a.id||id('a');a.name=String(a.name||`Agent ${i+1}`).slice(0,60);a.status=a.status==='suspended'?'suspended':'active';a.creditLimit=clampInt(a.creditLimit,0);a.cashier=!!a.cashier;a.moderator=!!a.moderator;a.games=unique((Array.isArray(a.games)?a.games:[]).filter(g=>GAMES.includes(g)))});state.users.forEach((u,i)=>{u.id=u.id||id('u');u.name=String(u.name||`User ${i+1}`).slice(0,60);u.status=u.status==='suspended'?'suspended':'active';u.credits=clampInt(u.credits,0);u.notes=String(u.notes||'').slice(0,500);const agent=state.agents.find(a=>a.id===u.agentId)||state.agents[0];u.agentId=agent?.id||'';u.games=unique((Array.isArray(u.games)?u.games:[]).filter(g=>agent?.games.includes(g))) });state.ledger.forEach(l=>{l.reversedBy=l.reversedBy||null;l.ref=l.ref||null});return state}
function load(){try{const current=localStorage.getItem(KEY);if(current)return normalize(JSON.parse(current));const legacy=localStorage.getItem(LEGACY_KEY);if(legacy){const migrated=normalize(JSON.parse(legacy));localStorage.setItem(KEY,JSON.stringify(migrated));return migrated}}catch{}return seed()}
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function actorRole(){return $('#actorRole')?.value||'Founder'}
function actorAgentId(){return $('#actorAgent')?.value||S.agents[0]?.id||''}
function actorLabel(){if(actorRole()==='Founder')return 'Founder';const a=S.agents.find(x=>x.id===actorAgentId());return `Agent:${a?.name||'Unknown'}`}
function currentAgent(){return S.agents.find(a=>a.id===actorAgentId())||null}
function isFounder(){return actorRole()==='Founder'}
function scopedAgents(){return isFounder()?S.agents:S.agents.filter(a=>a.id===actorAgentId())}
function scopedUsers(){return isFounder()?S.users:S.users.filter(u=>u.agentId===actorAgentId())}
function scopedLedger(){const userIds=new Set(scopedUsers().map(u=>u.id));return isFounder()?S.ledger:S.ledger.filter(l=>userIds.has(l.userId))}
function scopedAudit(){if(isFounder())return S.audit;const tag=`agent:${actorAgentId()}`;return S.audit.filter(a=>a.scope===tag||a.actor===actorLabel())}
function audit(action,details,scope){S.audit.unshift({id:id('x'),ts:now(),actor:actorLabel(),scope:scope||(!isFounder()?`agent:${actorAgentId()}`:'global'),action,details});S.audit=S.audit.slice(0,2000)}
function notify(message,danger=false){const t=$('#toast');if(!t){if(danger)alert(message);return}t.textContent=message;t.className=`toast on${danger?' danger':''}`;clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.className='toast',2600)}
function fail(message){notify(message,true);return false}
function agentName(agentId){return S.agents.find(a=>a.id===agentId)?.name||'Unassigned'}
function agentExposure(agentId,excludeUserId=null){return S.users.filter(u=>u.agentId===agentId&&u.id!==excludeUserId).reduce((n,u)=>n+clampInt(u.credits),0)}
function availableHeadroom(agentId,excludeUserId=null){const a=S.agents.find(x=>x.id===agentId);if(!a)return 0;return Math.max(0,a.creditLimit-agentExposure(agentId,excludeUserId))}
function canManageUser(user){return !!user&&(isFounder()||user.agentId===actorAgentId())}
function canManageAgent(agent){return !!agent&&isFounder()}
function canManageCreditsFor(user){if(!canManageUser(user))return false;if(isFounder())return true;const a=currentAgent();return !!a&&a.status==='active'&&a.cashier}
function usernameTaken(name,excludeId=null){const q=String(name).trim().toLowerCase();return S.users.some(u=>u.id!==excludeId&&u.name.trim().toLowerCase()===q)}
function ensureAgentActive(agent){return !!agent&&agent.status==='active'}
function inheritedGames(agentId){return S.agents.find(a=>a.id===agentId)?.games||[]}
function normalizeUserGames(user){const allowed=new Set(inheritedGames(user.agentId));user.games=unique((user.games||[]).filter(g=>allowed.has(g)))}

function applyCredit(userId,delta,reason,kind='adjustment',ref=null){const u=S.users.find(x=>x.id===userId);if(!u)return fail('User not found.');if(!canManageCreditsFor(u))return fail('This role does not have cashier authority for that user.');const d=Math.trunc(Number(delta));if(!Number.isFinite(d)||d===0)return fail('Credit amount must be a non-zero whole number.');if(u.status!=='active'&&kind!=='reversal')return fail('Suspended users cannot receive new credit adjustments.');const a=S.agents.find(x=>x.id===u.agentId);if(!a)return fail('User has no valid Agent.');if(!isFounder()&&!ensureAgentActive(a))return fail('The Agent is suspended.');const next=u.credits+d;if(next<0)return fail('That adjustment would make the user balance negative.');if(d>0){const projected=agentExposure(a.id,u.id)+next;if(projected>a.creditLimit)return fail(`Agent credit ceiling exceeded by ${(projected-a.creditLimit).toLocaleString()} credits.`)}u.credits=next;const entry={id:id('l'),ts:now(),actor:actorLabel(),userId:u.id,agentId:a.id,delta:d,reason:String(reason||'Adjustment').slice(0,250),kind,ref,openingBalance:next-d,balance:next,reversedBy:null};S.ledger.unshift(entry);audit(`credit_${kind}`,`${u.name}: ${d>=0?'+':''}${d.toLocaleString()} · ${entry.reason}`,`agent:${a.id}`);save();return entry}
function reverseEntry(ledgerId){const original=S.ledger.find(l=>l.id===ledgerId);if(!original)return fail('Ledger entry not found.');if(original.kind==='reversal')return fail('A reversal cannot itself be reversed. Create a new explicit adjustment instead.');if(original.reversedBy)return fail('This ledger entry has already been reversed.');const u=S.users.find(x=>x.id===original.userId);if(!u||!canManageCreditsFor(u))return fail('You cannot reverse this entry.');const reversal=applyCredit(original.userId,-original.delta,`Reversal of ${original.id}: ${original.reason}`,'reversal',original.id);if(!reversal)return false;original.reversedBy=reversal.id;save();return reversal}

function roleSync(){const select=$('#actorAgent');if(!select)return;select.innerHTML=S.agents.map(a=>`<option value="${a.id}">${esc(a.name)}${a.status==='suspended'?' (suspended)':''}</option>`).join('');select.disabled=isFounder();if(!select.value&&S.agents[0])select.value=S.agents[0].id;const a=currentAgent();const note=$('#scopeNote');if(note)note.innerHTML=isFounder()?'<b>Founder scope:</b> all Agents, users, credits, permissions and audit records are visible.':`<b>Agent scope:</b> ${esc(a?.name||'No Agent')} · ${a?.cashier?'cashier enabled':'no cashier authority'} · ${a?.moderator?'moderator enabled':'moderator off'} · only this Agent’s users and records are visible.`;document.querySelectorAll('[data-tab="agents"]').forEach(b=>b.disabled=!isFounder());$('#addAgent').disabled=!isFounder()}
function render(){roleSync();const users=scopedUsers(),agents=scopedAgents(),totalCredits=users.reduce((n,u)=>n+u.credits,0);$('#stats').innerHTML=[["Visible users",users.length],[isFounder()?"Agents":"My Agent",agents.length],["Virtual credits",totalCredits.toLocaleString()],["Active games",GAMES.length]].map(([a,b])=>`<div class="card"><span>${a}</span><strong>${b}</strong></div>`).join('');const low=users.filter(u=>u.status==='active'&&u.credits<250).slice(0,12);$('#lowBalances').innerHTML=low.length?low.map(u=>`<span class="pill danger">${esc(u.name)} · ${u.credits.toLocaleString()}</span>`).join(' '):'<span class="ok">No visible users below 250 credits.</span>';const agentChoices=isFounder()?S.agents:S.agents.filter(a=>a.id===actorAgentId());$('#quAgent').innerHTML=agentChoices.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('');$('#quAgent').disabled=!isFounder();$('#qcUser').innerHTML=users.map(u=>`<option value="${u.id}">${esc(u.name)} (${u.credits.toLocaleString()})</option>`).join('');$('#quickCredit button').disabled=!users.length||(!isFounder()&&!currentAgent()?.cashier);renderUsers();renderAgents();renderLedger();renderGames();renderAudit()}
function renderUsers(){const q=$('#userSearch').value.toLowerCase();const rows=scopedUsers().filter(u=>(`${u.name} ${agentName(u.agentId)} ${u.notes||''}`).toLowerCase().includes(q)).map(u=>`<tr><td><b>${esc(u.name)}</b><br><small>${esc(u.id)}</small></td><td>${esc(agentName(u.agentId))}</td><td><span class="pill ${u.status==='active'?'ok':'danger'}">${u.status}</span></td><td class="money">${u.credits.toLocaleString()}</td><td>${u.games?.length||0}/${inheritedGames(u.agentId).length}</td><td class="actions"><button onclick="creditUser('${u.id}',1)">+ Credits</button><button onclick="creditUser('${u.id}',-1)">− Credits</button><button onclick="toggleUser('${u.id}')">${u.status==='active'?'Suspend':'Reactivate'}</button><button onclick="editUser('${u.id}')">Edit</button><button onclick="editUserGames('${u.id}')">Games</button></td></tr>`).join('');$('#usersTable').innerHTML=`<div class="table"><table><thead><tr><th>User</th><th>Agent</th><th>Status</th><th>Credits</th><th>Games</th><th>Actions</th></tr></thead><tbody>${rows||'<tr><td colspan="6">No users in this scope.</td></tr>'}</tbody></table></div>`}
function renderAgents(){if(!isFounder()){const a=currentAgent();$('#agentsTable').innerHTML=a?`<article><h3>${esc(a.name)}</h3><p>This simulated Agent view cannot create or edit Agent accounts. Founder authority is required.</p></article>`:'';return}const rows=S.agents.map(a=>{const users=S.users.filter(u=>u.agentId===a.id),credits=users.reduce((n,u)=>n+u.credits,0);return `<tr><td><b>${esc(a.name)}</b><br><small>${a.id}</small></td><td><span class="pill ${a.status==='active'?'ok':'danger'}">${a.status}</span></td><td>${users.length}</td><td class="money">${credits.toLocaleString()}</td><td>${a.creditLimit.toLocaleString()}</td><td>${a.cashier?'Yes':'No'}</td><td>${a.moderator?'Yes':'No'}</td><td class="actions"><button onclick="editAgent('${a.id}')">Edit</button><button onclick="toggleAgent('${a.id}')">${a.status==='active'?'Suspend':'Reactivate'}</button></td></tr>`}).join('');$('#agentsTable').innerHTML=`<div class="table"><table><thead><tr><th>Agent</th><th>Status</th><th>Users</th><th>User balances</th><th>Credit ceiling</th><th>Cashier</th><th>Moderator</th><th>Actions</th></tr></thead><tbody>${rows}</tbody></table></div>`}
function renderLedger(){const q=$('#ledgerSearch').value.toLowerCase();const rows=scopedLedger().filter(l=>{const u=S.users.find(x=>x.id===l.userId);return `${l.reason} ${l.actor} ${u?.name||''}`.toLowerCase().includes(q)}).map(l=>{const user=S.users.find(u=>u.id===l.userId);const action=l.kind==='reversal'?'Reversal':l.reversedBy?`Reversed by ${esc(l.reversedBy)}`:`<button onclick="reverseLedger('${l.id}')">Reverse</button>`;return `<tr><td>${new Date(l.ts).toLocaleString()}</td><td>${esc(user?.name||l.userId)}</td><td class="${l.delta>=0?'ok':'danger'}">${l.delta>=0?'+':''}${l.delta.toLocaleString()}</td><td>${l.balance.toLocaleString()}</td><td>${esc(l.reason)}</td><td>${esc(l.actor)}</td><td>${action}</td></tr>`}).join('');$('#ledgerTable').innerHTML=`<div class="table"><table><thead><tr><th>Time</th><th>User</th><th>Change</th><th>Balance</th><th>Reason</th><th>Actor</th><th>Correction</th></tr></thead><tbody>${rows||'<tr><td colspan="7">No ledger entries in this scope.</td></tr>'}</tbody></table></div>`}
function renderGames(){const agentCards=scopedAgents().map(a=>`<article><h3>${esc(a.name)} <small>${a.games.length}/${GAMES.length} allowed</small></h3><div class="games">${GAMES.map(g=>`<label class="game"><input type="checkbox" ${a.games.includes(g)?'checked':''} ${!isFounder()?'disabled':''} onchange='setAgentGame("${a.id}",${JSON.stringify(g)},this.checked)'><span>${esc(g)}</span></label>`).join('')}</div></article>`).join('');const userCards=scopedUsers().map(u=>{const allowed=new Set(inheritedGames(u.agentId));return `<article class="access-group"><h4><span>${esc(u.name)}</span><small>${u.games.length}/${allowed.size} inherited choices</small></h4><div class="games">${GAMES.map(g=>{const inherited=allowed.has(g),on=u.games.includes(g);return `<label class="game ${inherited?'':'inherited-off'}"><input type="checkbox" ${on?'checked':''} ${!inherited?'disabled':''} onchange='setUserGame("${u.id}",${JSON.stringify(g)},this.checked)'><span>${esc(g)}</span>${!inherited?'<small>Agent blocked</small>':''}</label>`}).join('')}</div></article>`}).join('');$('#gamesPanel').innerHTML=agentCards+userCards}
function renderAudit(){const rows=scopedAudit().map(x=>`<tr><td>${new Date(x.ts).toLocaleString()}</td><td>${esc(x.actor)}</td><td>${esc(x.action)}</td><td>${esc(x.details)}</td></tr>`).join('');$('#auditTable').innerHTML=`<div class="table"><table><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Details</th></tr></thead><tbody>${rows||'<tr><td colspan="4">No audit records in this scope.</td></tr>'}</tbody></table></div>`}

function modal(title,body,onSave){const d=$('#modal');$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;d.showModal();$('#modalForm').onsubmit=e=>{e.preventDefault();const ok=onSave(new FormData(e.currentTarget));if(ok!==false){d.close();render()}}}
window.creditUser=(uid,sign)=>{const u=S.users.find(x=>x.id===uid);if(!canManageCreditsFor(u))return fail('No cashier permission for this user.');const amount=clampInt(prompt(sign>0?'Credits to add':'Credits to remove','100'),0);if(!amount)return;const reason=prompt('Reason','Manual adjustment')||'Manual adjustment';if(applyCredit(uid,sign*amount,reason)){notify('Virtual-credit ledger updated.');render()}};
window.reverseLedger=lid=>{const l=S.ledger.find(x=>x.id===lid);if(!l)return;if(!confirm('Create one equal-and-opposite ledger entry? The original record remains unchanged.'))return;if(reverseEntry(lid)){notify('Compensating reversal created.');render()}};
window.toggleUser=uid=>{const u=S.users.find(x=>x.id===uid);if(!canManageUser(u))return fail('User is outside this Agent scope.');u.status=u.status==='active'?'suspended':'active';audit('user_status',`${u.name} -> ${u.status}`,`agent:${u.agentId}`);save();render()};
window.toggleAgent=aid=>{const a=S.agents.find(x=>x.id===aid);if(!canManageAgent(a))return fail('Founder authority required.');a.status=a.status==='active'?'suspended':'active';audit('agent_status',`${a.name} -> ${a.status}`,`agent:${a.id}`);save();render()};
window.setAgentGame=(aid,g,on)=>{const a=S.agents.find(x=>x.id===aid);if(!canManageAgent(a))return fail('Founder authority required.');if(!GAMES.includes(g))return;const before=a.games.length;a.games=on?unique([...a.games,g]):a.games.filter(x=>x!==g);if(!on)S.users.filter(u=>u.agentId===aid).forEach(u=>u.games=u.games.filter(x=>x!==g));if(a.games.length!==before){audit('agent_game_access',`${a.name}: ${g} ${on?'enabled':'disabled'}; user access reconciled`,`agent:${aid}`);save();render()}};
window.setUserGame=(uid,g,on)=>{const u=S.users.find(x=>x.id===uid);if(!canManageUser(u))return fail('User is outside this Agent scope.');if(!inheritedGames(u.agentId).includes(g))return fail('Agent permission does not include this game.');u.games=on?unique([...u.games,g]):u.games.filter(x=>x!==g);audit('user_game_access',`${u.name}: ${g} ${on?'enabled':'disabled'}`,`agent:${u.agentId}`);save();render()};
window.editUser=uid=>{const u=S.users.find(x=>x.id===uid);if(!canManageUser(u))return fail('User is outside this Agent scope.');const choices=(isFounder()?S.agents:S.agents.filter(a=>a.id===actorAgentId())).map(a=>`<option value="${a.id}" ${a.id===u.agentId?'selected':''}>${esc(a.name)}</option>`).join('');modal('Edit user',`<label>Username<input name="name" value="${esc(u.name)}" maxlength="50" required></label><label>Agent<select name="agent" ${!isFounder()?'disabled':''}>${choices}</select></label><label>Notes<textarea name="notes" maxlength="500" rows="5">${esc(u.notes||'')}</textarea></label>`,f=>{const name=String(f.get('name')||'').trim();const nextAgent=isFounder()?String(f.get('agent')||u.agentId):u.agentId;if(!name)return fail('Username is required.');if(usernameTaken(name,u.id))return fail('Username already exists.');const a=S.agents.find(x=>x.id===nextAgent);if(!a)return fail('Agent not found.');if(agentExposure(a.id,u.id)+u.credits>a.creditLimit)return fail('That Agent does not have enough credit-ceiling headroom for this user balance.');const oldAgent=u.agentId;u.name=name;u.agentId=a.id;u.notes=String(f.get('notes')||'').slice(0,500);normalizeUserGames(u);audit('user_edit',`${u.name}${oldAgent!==u.agentId?` reassigned ${agentName(oldAgent)} -> ${a.name}`:''}`,`agent:${u.agentId}`);save();return true})};
window.editUserGames=uid=>{const u=S.users.find(x=>x.id===uid);if(!canManageUser(u))return fail('User is outside this Agent scope.');const allowed=new Set(inheritedGames(u.agentId));modal(`Game access · ${u.name}`,`<div class="games">${GAMES.map(g=>`<label class="game ${allowed.has(g)?'':'inherited-off'}"><input name="game" value="${esc(g)}" type="checkbox" ${u.games.includes(g)?'checked':''} ${!allowed.has(g)?'disabled':''}><span>${esc(g)}</span>${!allowed.has(g)?'<small>Agent blocked</small>':''}</label>`).join('')}</div>`,f=>{u.games=unique(f.getAll('game').filter(g=>allowed.has(g)));audit('user_game_access_bulk',`${u.name}: ${u.games.length} games enabled`,`agent:${u.agentId}`);save();return true})};
window.editAgent=aid=>{const a=S.agents.find(x=>x.id===aid);if(!canManageAgent(a))return fail('Founder authority required.');modal('Edit agent',`<label>Agent name<input name="name" value="${esc(a.name)}" maxlength="60" required></label><label>Credit ceiling<input name="limit" type="number" min="0" step="1" value="${a.creditLimit}"></label><label class="check"><input name="cashier" type="checkbox" ${a.cashier?'checked':''}> Cashier / credit authority</label><label class="check"><input name="moderator" type="checkbox" ${a.moderator?'checked':''}> Moderator authority</label>`,f=>{const name=String(f.get('name')||'').trim(),limit=clampInt(f.get('limit'),0);if(!name)return fail('Agent name is required.');if(limit<agentExposure(a.id))return fail('Credit ceiling cannot be below current combined user balances.');a.name=name;a.creditLimit=limit;a.cashier=f.get('cashier')==='on';a.moderator=f.get('moderator')==='on';audit('agent_edit',`${a.name}: ceiling ${limit.toLocaleString()}, cashier ${a.cashier}, moderator ${a.moderator}`,`agent:${a.id}`);save();return true})};

$('#quickUser').onsubmit=e=>{e.preventDefault();const name=$('#quName').value.trim(),aid=isFounder()?$('#quAgent').value:actorAgentId(),credits=clampInt($('#quCredits').value,0),a=S.agents.find(x=>x.id===aid);if(!name)return fail('Username is required.');if(usernameTaken(name))return fail('Username already exists.');if(!ensureAgentActive(a))return fail('The selected Agent is suspended.');if(agentExposure(a.id)+credits>a.creditLimit)return fail('Opening balance exceeds the Agent credit ceiling.');const u={id:id('u'),name,agentId:a.id,status:'active',credits:0,games:[...a.games],notes:''};S.users.push(u);audit('user_create',`${name} under ${a.name}`,`agent:${a.id}`);save();if(credits&&!applyCredit(u.id,credits,'Opening virtual-credit balance','opening')){S.users=S.users.filter(x=>x.id!==u.id);save();return}e.target.reset();$('#quCredits').value='1000';notify('User created.');render()};
$('#quickCredit').onsubmit=e=>{e.preventDefault();const uid=$('#qcUser').value,amount=clampInt($('#qcAmount').value,0),reason=$('#qcReason').value||'Adjustment';if(!amount)return fail('Enter a credit amount.');if(applyCredit(uid,amount,reason)){notify('Credits applied.');render()}};
$('#addUser').onclick=()=>{document.querySelector('[data-tab="dashboard"]').click();$('#quName').focus()};
$('#addAgent').onclick=()=>{if(!isFounder())return fail('Founder authority required.');modal('Add agent',`<label>Agent name<input name="name" maxlength="60" required></label><label>Credit ceiling<input name="limit" type="number" min="0" step="1" value="10000"></label><label class="check"><input name="cashier" type="checkbox" checked> Cashier / credit authority</label><label class="check"><input name="moderator" type="checkbox"> Moderator authority</label>`,f=>{const name=String(f.get('name')||'').trim();if(!name)return fail('Agent name is required.');const a={id:id('a'),name,status:'active',creditLimit:clampInt(f.get('limit'),0),cashier:f.get('cashier')==='on',moderator:f.get('moderator')==='on',games:[...GAMES]};S.agents.push(a);audit('agent_create',a.name,`agent:${a.id}`);save();return true})};
$('#bulkUsers').onclick=()=>{const choices=(isFounder()?S.agents:S.agents.filter(a=>a.id===actorAgentId())).map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('');modal('Bulk create users',`<label>Usernames, one per line<textarea name="names" rows="10" required></textarea></label><label>Agent<select name="agent" ${!isFounder()?'disabled':''}>${choices}</select></label><label>Opening credits per user<input name="credits" type="number" min="0" step="1" value="500"></label>`,f=>{const aid=isFounder()?String(f.get('agent')||''):actorAgentId(),a=S.agents.find(x=>x.id===aid),credits=clampInt(f.get('credits'),0);if(!ensureAgentActive(a))return fail('Agent is suspended.');const names=String(f.get('names')||'').split(/\n+/).map(x=>x.trim()).filter(Boolean).slice(0,100);const deduped=unique(names.map(n=>n.toLowerCase()));if(deduped.length!==names.length)return fail('Bulk list contains duplicate usernames.');const collision=names.find(n=>usernameTaken(n));if(collision)return fail(`Username already exists: ${collision}`);const required=credits*names.length;if(agentExposure(a.id)+required>a.creditLimit)return fail(`Bulk opening balances need ${required.toLocaleString()} credits but exceed the Agent ceiling.`);names.forEach(name=>{const u={id:id('u'),name,agentId:a.id,status:'active',credits:0,games:[...a.games],notes:'Bulk created'};S.users.push(u);audit('user_create',`${name} bulk under ${a.name}`,`agent:${a.id}`);if(credits)applyCredit(u.id,credits,'Bulk opening balance','opening')});save();notify(`${names.length} users created.`);return true})};
$('#exportData').onclick=()=>{const payload=isFounder()?S:{version:S.version,agents:scopedAgents(),users:scopedUsers(),ledger:scopedLedger(),audit:scopedAudit()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`fsa-founder-console-${isFounder()?'founder':'agent'}-export.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0)};
$('#userSearch').oninput=renderUsers;$('#ledgerSearch').oninput=renderLedger;$('#actorRole').onchange=()=>{roleSync();render()};$('#actorAgent').onchange=render;
document.querySelectorAll('nav button[data-tab]').forEach(b=>b.onclick=()=>{if(b.disabled)return;document.querySelectorAll('nav button[data-tab],.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});

window.__FSA_ADMIN_TEST__={normalize,agentExposure,availableHeadroom,usernameTaken,inheritedGames,applyCredit,reverseEntry,getState:()=>S,setState:v=>{S=normalize(v);save()},setActor:(role,agentId)=>{if($('#actorRole'))$('#actorRole').value=role;if($('#actorAgent')&&agentId)$('#actorAgent').value=agentId}};
render();