const GAMES=["Reef Run","Dragon Depths","Pirate’s Plunder","Atlantis Rising","Ice Tide","Lava Reef","Storm Seas","Jade Dragon","Neon Ocean","Ancient Ruins","Mecha Marine","Coral Chaos","Kraken’s Lair","Treasure Trials","Boss Rush","Ocean Fortune","Treasure Reels","Siren’s Gold","Legend of Atlantis","Shark Jackpot","Pearl Rush","Kraken Spins","Reef Riches","Lucky Tide","Deep Diamonds","Golden Anchor","Mermaid’s Treasure","Pirate Jackpot","Coral Cash","Neptune’s Wheel","Sea King 777","Ocean Wilds","Diamond Dolphin","Wild Pearls","Treasure Temple"];
const KEY="fsa.founder.console.v1";
let S=load();
function load(){try{return JSON.parse(localStorage.getItem(KEY))||seed()}catch{return seed()}}
function seed(){return {agents:[{id:"a1",name:"House Agent",status:"active",creditLimit:50000,cashier:true,moderator:false,games:[...GAMES]}],users:[{id:"u1",name:"ReefRider",agentId:"a1",status:"active",credits:12450,games:[...GAMES.slice(0,15)],notes:"Demo user"}],ledger:[],audit:[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function id(p){return p+Math.random().toString(36).slice(2,9)}
function now(){return new Date().toISOString()}
function actor(){return document.querySelector("#actorRole").value}
function audit(action,details){S.audit.unshift({id:id("x"),ts:now(),actor:actor(),action,details});S.audit=S.audit.slice(0,1000)}
function ledger(userId,delta,reason,kind="adjustment",ref=null){const u=S.users.find(x=>x.id===userId);if(!u)return;u.credits=Math.max(0,(u.credits||0)+delta);S.ledger.unshift({id:id("l"),ts:now(),actor:actor(),userId,delta,reason,kind,ref,balance:u.credits});audit("credit_"+kind,`${u.name}: ${delta>=0?"+":""}${delta} · ${reason}`);save()}
function agentName(id){return S.agents.find(a=>a.id===id)?.name||"Unassigned"}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function canManageCredits(){return actor()==="Founder"||actor()==="Agent"}
function render(){const activeUsers=S.users.filter(u=>u.status==="active");const totalCredits=S.users.reduce((n,u)=>n+(u.credits||0),0);document.querySelector("#stats").innerHTML=[["Users",S.users.length],["Agents",S.agents.length],["Virtual credits",totalCredits.toLocaleString()],["Active games",GAMES.length]].map(([a,b])=>`<div class=card><span>${a}</span><strong>${b}</strong></div>`).join("");const low=activeUsers.filter(u=>u.credits<250).slice(0,10);document.querySelector("#lowBalances").innerHTML=low.length?low.map(u=>`<span class="pill danger">${esc(u.name)} · ${u.credits}</span>`).join(" "):'<span class="ok">No users below 250 credits.</span>';document.querySelector("#qcUser").innerHTML=S.users.map(u=>`<option value="${u.id}">${esc(u.name)} (${u.credits})</option>`).join("");document.querySelector("#quAgent").innerHTML=S.agents.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join("");renderUsers();renderAgents();renderLedger();renderGames();renderAudit()}
function renderUsers(){const q=document.querySelector("#userSearch").value.toLowerCase();const rows=S.users.filter(u=>(u.name+" "+agentName(u.agentId)).toLowerCase().includes(q)).map(u=>`<tr><td><b>${esc(u.name)}</b><br><small>${esc(u.id)}</small></td><td>${esc(agentName(u.agentId))}</td><td><span class="pill ${u.status==="active"?"ok":"danger"}">${u.status}</span></td><td class=money>${u.credits.toLocaleString()}</td><td>${u.games?.length||0}/${GAMES.length}</td><td><button onclick="creditUser('${u.id}',1)">+ Credits</button> <button onclick="creditUser('${u.id}',-1)">− Credits</button> <button onclick="toggleUser('${u.id}')">${u.status==="active"?"Suspend":"Reactivate"}</button> <button onclick="editUser('${u.id}')">Edit</button></td></tr>`).join("");document.querySelector("#usersTable").innerHTML=`<div class=table><table><thead><tr><th>User</th><th>Agent</th><th>Status</th><th>Credits</th><th>Games</th><th>Actions</th></tr></thead><tbody>${rows}</tbody></table></div>`}
function renderAgents(){const rows=S.agents.map(a=>{const users=S.users.filter(u=>u.agentId===a.id);const credits=users.reduce((n,u)=>n+u.credits,0);return `<tr><td><b>${esc(a.name)}</b><br><small>${a.id}</small></td><td>${a.status}</td><td>${users.length}</td><td class=money>${credits.toLocaleString()}</td><td>${a.creditLimit.toLocaleString()}</td><td>${a.cashier?"Yes":"No"}</td><td>${a.moderator?"Yes":"No"}</td><td><button onclick="editAgent('${a.id}')">Edit</button> <button onclick="toggleAgent('${a.id}')">${a.status==="active"?"Suspend":"Reactivate"}</button></td></tr>`}).join("");document.querySelector("#agentsTable").innerHTML=`<div class=table><table><thead><tr><th>Agent</th><th>Status</th><th>Users</th><th>User balances</th><th>Credit ceiling</th><th>Cashier</th><th>Moderator</th><th></th></tr></thead><tbody>${rows}</tbody></table></div>`}
function renderLedger(){const q=document.querySelector("#ledgerSearch").value.toLowerCase();const rows=S.ledger.filter(l=>(l.reason+" "+l.actor).toLowerCase().includes(q)).map(l=>`<tr><td>${new Date(l.ts).toLocaleString()}</td><td>${esc(S.users.find(u=>u.id===l.userId)?.name||l.userId)}</td><td class="${l.delta>=0?"ok":"danger"}">${l.delta>=0?"+":""}${l.delta}</td><td>${l.balance}</td><td>${esc(l.reason)}</td><td>${esc(l.actor)}</td><td>${l.kind==="reversal"?"Reversal":`<button onclick="reverseLedger('${l.id}')">Reverse</button>`}</td></tr>`).join("");document.querySelector("#ledgerTable").innerHTML=`<div class=table><table><thead><tr><th>Time</th><th>User</th><th>Change</th><th>Balance</th><th>Reason</th><th>Actor</th><th></th></tr></thead><tbody>${rows}</tbody></table></div>`}
function renderGames(){document.querySelector("#gamesPanel").innerHTML=S.agents.map(a=>`<article><h3>${esc(a.name)} <small>${a.games.length}/${GAMES.length} allowed</small></h3><div class=games>${GAMES.map(g=>`<label class=game><input type=checkbox ${a.games.includes(g)?"checked":""} onchange='setAgentGame("${a.id}",${JSON.stringify(g)},this.checked)'> ${esc(g)}</label>`).join("")}</div></article>`).join("")}
function renderAudit(){document.querySelector("#auditTable").innerHTML=`<div class=table><table><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Details</th></tr></thead><tbody>${S.audit.map(x=>`<tr><td>${new Date(x.ts).toLocaleString()}</td><td>${esc(x.actor)}</td><td>${esc(x.action)}</td><td>${esc(x.details)}</td></tr>`).join("")}</tbody></table></div>`}
function modal(title,body,onSave){const d=document.querySelector("#modal");document.querySelector("#modalTitle").textContent=title;document.querySelector("#modalBody").innerHTML=body;d.showModal();document.querySelector("#modalForm").onsubmit=e=>{e.preventDefault();onSave(new FormData(e.currentTarget));d.close();render()}}
window.creditUser=(uid,sign)=>{if(!canManageCredits())return alert("No cashier permission.");const amount=Number(prompt(sign>0?"Credits to add":"Credits to remove","100"));if(!amount||amount<1)return;const reason=prompt("Reason","Manual adjustment")||"Manual adjustment";ledger(uid,sign*amount,reason);render()};
window.reverseLedger=(lid)=>{const l=S.ledger.find(x=>x.id===lid);if(!l)return;if(!confirm("Create an equal and opposite ledger entry? Original history stays unchanged."))return;ledger(l.userId,-l.delta,`Reversal of ${l.id}: ${l.reason}`,"reversal",l.id);render()};
window.toggleUser=uid=>{const u=S.users.find(x=>x.id===uid);u.status=u.status==="active"?"suspended":"active";audit("user_status",`${u.name} -> ${u.status}`);save();render()};
window.toggleAgent=aid=>{const a=S.agents.find(x=>x.id===aid);a.status=a.status==="active"?"suspended":"active";audit("agent_status",`${a.name} -> ${a.status}`);save();render()};
window.setAgentGame=(aid,g,on)=>{const a=S.agents.find(x=>x.id===aid);a.games=on?[...new Set([...a.games,g])]:a.games.filter(x=>x!==g);audit("agent_game_access",`${a.name}: ${g} ${on?"enabled":"disabled"}`);save()};
window.editUser=uid=>{const u=S.users.find(x=>x.id===uid);modal("Edit user",`<input name=name value="${esc(u.name)}" required><select name=agent>${S.agents.map(a=>`<option value="${a.id}" ${a.id===u.agentId?"selected":""}>${esc(a.name)}</option>`).join("")}</select><textarea name=notes placeholder=Notes>${esc(u.notes||"")}</textarea>`,f=>{u.name=f.get("name");u.agentId=f.get("agent");u.notes=f.get("notes");audit("user_edit",u.name);save()})};
window.editAgent=aid=>{const a=S.agents.find(x=>x.id===aid);modal("Edit agent",`<input name=name value="${esc(a.name)}" required><input name=limit type=number min=0 value="${a.creditLimit}"><label><input name=cashier type=checkbox ${a.cashier?"checked":""}> Cashier / credit authority</label><label><input name=moderator type=checkbox ${a.moderator?"checked":""}> Moderator</label>`,f=>{a.name=f.get("name");a.creditLimit=Number(f.get("limit"));a.cashier=f.get("cashier")==="on";a.moderator=f.get("moderator")==="on";audit("agent_edit",a.name);save()})};
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button,.tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelector("#"+b.dataset.tab).classList.add("active")});
document.querySelector("#quickUser").onsubmit=e=>{e.preventDefault();const name=document.querySelector("#quName").value.trim();const aid=document.querySelector("#quAgent").value;const cr=Number(document.querySelector("#quCredits").value||0);const a=S.agents.find(x=>x.id===aid);if(actor()==="Agent"&&a?.status!=="active")return alert("Agent is suspended.");const u={id:id("u"),name,agentId:aid,status:"active",credits:0,games:[...(a?.games||[])],notes:""};S.users.push(u);audit("user_create",`${name} under ${a?.name}`);save();if(cr)ledger(u.id,cr,"Opening virtual-credit balance","opening");e.target.reset();render()};
document.querySelector("#quickCredit").onsubmit=e=>{e.preventDefault();ledger(document.querySelector("#qcUser").value,Number(document.querySelector("#qcAmount").value),document.querySelector("#qcReason").value||"Adjustment");render()};
document.querySelector("#addUser").onclick=()=>document.querySelector("#quName").focus();
document.querySelector("#addAgent").onclick=()=>modal("Add agent",`<input name=name placeholder="Agent name" required><input name=limit type=number min=0 value=10000><label><input name=cashier type=checkbox checked> Cashier / credit authority</label><label><input name=moderator type=checkbox> Moderator</label>`,f=>{const a={id:id("a"),name:f.get("name"),status:"active",creditLimit:Number(f.get("limit")),cashier:f.get("cashier")==="on",moderator:f.get("moderator")==="on",games:[...GAMES]};S.agents.push(a);audit("agent_create",a.name);save()});
document.querySelector("#bulkUsers").onclick=()=>modal("Bulk create users",`<textarea name=names rows=10 placeholder="One username per line" required></textarea><select name=agent>${S.agents.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join("")}</select><input name=credits type=number min=0 value=500>`,f=>{const aid=f.get("agent"),cr=Number(f.get("credits"));const a=S.agents.find(x=>x.id===aid);String(f.get("names")).split(/\n+/).map(x=>x.trim()).filter(Boolean).slice(0,100).forEach(name=>{const u={id:id("u"),name,agentId:aid,status:"active",credits:0,games:[...(a?.games||[])],notes:"Bulk created"};S.users.push(u);audit("user_create",`${name} bulk under ${a?.name}`);if(cr)ledger(u.id,cr,"Bulk opening balance","opening")});save()});
document.querySelector("#exportData").onclick=()=>{const blob=new Blob([JSON.stringify(S,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="fsa-founder-console-export.json";a.click();URL.revokeObjectURL(a.href)};
document.querySelector("#userSearch").oninput=renderUsers;document.querySelector("#ledgerSearch").oninput=renderLedger;document.querySelector("#actorRole").onchange=render;render();