import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4'
const SUPABASE_URL='https://nqcshihyfhthywpseilx.supabase.co'
const SUPABASE_KEY='sb_publishable_lD--sdVpwV9djLF28XW1Jg_95DPa58G'
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:'pkce'}})
const $=s=>document.querySelector(s)
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))
function toast(t,bad=false){const e=$('#toast');if(!e)return;e.textContent=t;e.className=`toast on${bad?' danger':''}`;setTimeout(()=>e.className='toast',3500)}
function text(e){return String(e?.message||e?.error_description||e?.error||e||'Unknown error').replace(/^Error:\s*/,'')}
async function invoke(body){const {data,error}=await supabase.functions.invoke('fsa-founder-admin',{body});if(error)throw error;if(data?.error)throw new Error(data.error);return data}
async function agents(){const {data,error}=await supabase.from('fsa_agents').select('id,display_name,username,distributor_id,status').eq('status','active').order('display_name');if(error)throw error;return data||[]}
async function currentProfile(){const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Operator session expired. Sign in again.');const {data,error}=await supabase.from('fsa_operator_profiles').select('role,agent_id,distributor_id,status').eq('user_id',session.user.id).single();if(error)throw error;if(data.status!=='active')throw new Error('Operator account is suspended.');return data}
async function createNetworkPlayer({email,username,display,agent,credits=0,notes=''}){if(!email)throw new Error('Email is required for an authenticated network player.');const p=await currentProfile();const aid=p.role==='agent'?p.agent_id:agent;if(!aid)throw new Error('Choose an Agent.');return invoke({action:'invite_player',email,username,display_name:display||username,agent_id:aid,opening_balance:Number(credits||0),notes,game_ids:null})}
function ensureModal(){if($('#networkPlayerDialog'))return;document.body.insertAdjacentHTML('beforeend',`<dialog id="networkPlayerDialog"><form id="networkPlayerForm"><h2>Create authenticated player</h2><div id="networkPlayerBody" class="stack"></div><p class="muted">An Auth invitation is sent to the player. All inherited fish-game permissions and virtual credits remain server-authoritative.</p><menu><button type="button" id="networkPlayerCancel">Cancel</button><button id="networkPlayerSave">Create + invite</button></menu></form></dialog>`);$('#networkPlayerCancel').onclick=()=>$('#networkPlayerDialog').close();$('#networkPlayerForm').onsubmit=submitDialog}
async function openDialog(){try{const [aa,p]=await Promise.all([agents(),currentProfile()]);ensureModal();const allowed=p.role==='agent'?aa.filter(a=>a.id===p.agent_id):aa;$('#networkPlayerBody').innerHTML=`<label>Email<input name="email" type="email" autocomplete="email" required></label><label>Username<input name="username" maxlength="60" required></label><label>Display name<input name="display" maxlength="80"></label><label>Agent<select name="agent" ${p.role==='agent'?'disabled':''}>${allowed.map(a=>`<option value="${a.id}">${esc(a.display_name||a.username)}</option>`).join('')}</select></label><label>Opening virtual credits<input name="credits" type="number" min="0" step="1" value="0"></label><label>Notes<textarea name="notes" maxlength="500"></textarea></label>`;$('#networkPlayerDialog').showModal()}catch(e){toast(text(e),true)}}
async function submitDialog(e){e.preventDefault();const save=$('#networkPlayerSave');save.disabled=true;try{const fd=new FormData(e.currentTarget),r=await createNetworkPlayer({email:fd.get('email'),username:fd.get('username'),display:fd.get('display'),agent:fd.get('agent'),credits:fd.get('credits'),notes:fd.get('notes')});toast(r.invited?'Authenticated player created and invitation sent.':'Authenticated player linked.');$('#networkPlayerDialog').close();setTimeout(()=>location.reload(),550)}catch(e){toast(text(e),true)}finally{save.disabled=false}}
async function quickCreate(e){e.preventDefault();e.stopImmediatePropagation();try{const r=await createNetworkPlayer({email:$('#quEmail').value.trim(),username:$('#quName').value.trim(),display:$('#quDisplay').value.trim(),agent:$('#quAgent').value,credits:$('#quCredits').value,notes:''});toast(r.invited?'Authenticated player created and invitation sent.':'Authenticated player linked.');$('#quEmail').value='';$('#quName').value='';$('#quDisplay').value='';setTimeout(()=>location.reload(),550)}catch(err){toast(text(err),true)}}
function wire(){const q=$('#quickUser');if(q)q.addEventListener('submit',quickCreate,true);const b=$('#addUser');if(b)b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();openDialog()},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire,{once:true});else wire()
