import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4'

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!
const SERVICE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const ANON_KEY = Deno.env.get('SUPABASE_ANON_KEY')!
const ADMIN_URL = 'https://anastaysia94-sudo.github.io/fish-shooter-arcade/admin/'
const PLAYER_URL = 'https://anastaysia94-sudo.github.io/fish-shooter-arcade/'
const ADMIN_ORIGIN = 'https://anastaysia94-sudo.github.io'
const admin = createClient(SUPABASE_URL, SERVICE_KEY, { auth: { persistSession: false, autoRefreshToken: false } })

function corsHeaders(req: Request) {
  const origin = req.headers.get('origin')
  return {'access-control-allow-origin': origin === ADMIN_ORIGIN ? origin : ADMIN_ORIGIN,'access-control-allow-headers':'authorization, x-client-info, apikey, content-type','access-control-allow-methods':'POST, OPTIONS','vary':'Origin'}
}
function json(req: Request, body: unknown, status = 200) { return new Response(JSON.stringify(body), { status, headers: { 'content-type':'application/json; charset=utf-8','cache-control':'no-store',...corsHeaders(req) } }) }
function jwtPayload(token: string): Record<string, unknown> { const part=token.split('.')[1]; if(!part)return {}; const normalized=part.replace(/-/g,'+').replace(/_/g,'/'); try{return JSON.parse(atob(normalized.padEnd(Math.ceil(normalized.length/4)*4,'=')))}catch{return {}} }
async function findUserByEmail(email:string){ for(let page=1;page<=100;page++){const {data,error}=await admin.auth.admin.listUsers({page,perPage:100});if(error)throw error;const found=data.users.find(u=>(u.email||'').toLowerCase()===email.toLowerCase());if(found)return found;if(data.users.length<100)break} return null }
async function operatorFromRequest(req:Request){ const authHeader=req.headers.get('authorization')||'';const token=authHeader.replace(/^Bearer\s+/i,'');if(!token)throw new Error('FSA_AUTH_REQUIRED');const {data:userData,error:userError}=await admin.auth.getUser(token);if(userError||!userData.user)throw new Error('FSA_AUTH_INVALID');if(jwtPayload(token).aal!=='aal2')throw new Error('FSA_MFA_REQUIRED');const {data:profile,error}=await admin.from('fsa_operator_profiles').select('user_id,role,status,distributor_id,agent_id').eq('user_id',userData.user.id).maybeSingle();if(error)throw error;if(!profile||profile.status!=='active'||!['founder','distributor','agent'].includes(profile.role))throw new Error('FSA_OPERATOR_SCOPE_REQUIRED');let distributor:any=null,agent:any=null;if(profile.role==='distributor'){const r=await admin.from('fsa_distributors').select('id,status,can_manage_agents,can_manage_users,can_cashier,can_moderate,credit_ceiling').eq('id',profile.distributor_id).maybeSingle();if(r.error)throw r.error;if(!r.data||r.data.status!=='active')throw new Error('FSA_DISTRIBUTOR_INACTIVE');distributor=r.data}if(profile.role==='agent'){const r=await admin.from('fsa_agents').select('id,distributor_id,status,can_manage_users,can_cashier,can_moderate,credit_ceiling').eq('id',profile.agent_id).maybeSingle();if(r.error)throw r.error;if(!r.data||r.data.status!=='active')throw new Error('FSA_AGENT_INACTIVE');agent=r.data;const d=await admin.from('fsa_distributors').select('id,status').eq('id',agent.distributor_id).maybeSingle();if(d.error)throw d.error;if(!d.data||d.data.status!=='active')throw new Error('FSA_DISTRIBUTOR_INACTIVE')}const caller=createClient(SUPABASE_URL,ANON_KEY,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false,autoRefreshToken:false}});return {user:userData.user,profile,distributor,agent,caller}}
async function ensureUnlinkedAuthUser(userId:string){const [op,player]=await Promise.all([admin.from('fsa_operator_profiles').select('user_id').eq('user_id',userId).maybeSingle(),admin.from('fsa_players').select('id').eq('auth_user_id',userId).maybeSingle()]);if(op.error)throw op.error;if(player.error)throw player.error;if(op.data||player.data)throw new Error('FSA_AUTH_ACCOUNT_ALREADY_LINKED')}
async function provisionAuth(email:string,displayName:string,role:string,redirectTo:string){let authUser=await findUserByEmail(email),invited=false;if(!authUser){const {data,error}=await admin.auth.admin.inviteUserByEmail(email,{data:{display_name:displayName,app:'fsa',fsa_role:role},redirectTo});if(error)throw error;authUser=data.user;invited=true}if(!authUser)throw new Error('AUTH_USER_CREATE_FAILED');await ensureUnlinkedAuthUser(authUser.id);return {authUser,invited}}
function identity(body:any){const email=String(body.email||'').trim().toLowerCase(),username=String(body.username||'').trim(),displayName=String(body.display_name||username).trim();if(!email||!email.includes('@'))throw new Error('INVALID_EMAIL');if(!/^[A-Za-z0-9][A-Za-z0-9._-]{1,59}$/.test(username))throw new Error('INVALID_USERNAME');if(displayName.length<1||displayName.length>80)throw new Error('INVALID_DISPLAY_NAME');return {email,username,displayName}}
function ceiling(body:any){const raw=Number(body.credit_ceiling||0);if(!Number.isFinite(raw)||raw<0||!Number.isSafeInteger(Math.floor(raw)))throw new Error('INVALID_CEILING');return Math.floor(raw)}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders(req)});if(req.method!=='POST')return json(req,{error:'METHOD_NOT_ALLOWED'},405);try{const operator=await operatorFromRequest(req);const body:any=await req.json().catch(()=>({}));const action=String(body.action||'');if(action==='health')return json(req,{ok:true,role:operator.profile.role,aal:'aal2',distributor_id:operator.profile.distributor_id||operator.agent?.distributor_id||null,agent_id:operator.profile.agent_id||null});
if(action==='invite_distributor'){if(operator.profile.role!=='founder')throw new Error('FSA_FOUNDER_REQUIRED');const {email,username,displayName}=identity(body),creditCeiling=ceiling(body);const {authUser,invited}=await provisionAuth(email,displayName,'distributor',ADMIN_URL);try{const requested=Array.isArray(body.game_ids)?body.game_ids.map(String):null;const {data:distributorId,error}=await operator.caller.rpc('fsa_rpc_provision_distributor_operator',{p_auth_user_id:authUser.id,p_username:username,p_display_name:displayName,p_credit_ceiling:creditCeiling,p_can_manage_agents:Boolean(body.can_manage_agents),p_can_manage_users:Boolean(body.can_manage_users),p_can_cashier:Boolean(body.can_cashier),p_can_moderate:Boolean(body.can_moderate),p_game_ids:requested?.length?requested:null});if(error)throw error;const r=await admin.from('fsa_distributors').select('id,username,display_name,status,credit_ceiling,can_manage_agents,can_manage_users,can_cashier,can_moderate').eq('id',distributorId).single();if(r.error)throw r.error;return json(req,{ok:true,invited,distributor:r.data})}catch(e){if(invited)await admin.auth.admin.deleteUser(authUser.id).catch(()=>undefined);throw e}}
if(action==='invite_agent'){if(!['founder','distributor'].includes(operator.profile.role))throw new Error('FSA_MANAGE_AGENTS_REQUIRED');const {email,username,displayName}=identity(body),creditCeiling=ceiling(body);let distributorId=String(body.distributor_id||'');if(operator.profile.role==='distributor'){if(!operator.distributor?.can_manage_agents)throw new Error('FSA_MANAGE_AGENTS_REQUIRED');distributorId=String(operator.profile.distributor_id)}if(!distributorId)throw new Error('FSA_DISTRIBUTOR_REQUIRED');const {authUser,invited}=await provisionAuth(email,displayName,'agent',ADMIN_URL);try{const requested=Array.isArray(body.game_ids)?body.game_ids.map(String):null;const {data:agentId,error}=await operator.caller.rpc('fsa_rpc_provision_agent_operator',{p_auth_user_id:authUser.id,p_distributor_id:distributorId,p_username:username,p_display_name:displayName,p_credit_ceiling:creditCeiling,p_can_manage_users:body.can_manage_users!==false,p_can_cashier:Boolean(body.can_cashier),p_can_moderate:Boolean(body.can_moderate),p_game_ids:requested?.length?requested:null});if(error)throw error;const r=await admin.from('fsa_agents').select('id,distributor_id,username,display_name,status,credit_ceiling,can_manage_users,can_cashier,can_moderate').eq('id',agentId).single();if(r.error)throw r.error;return json(req,{ok:true,invited,agent:r.data})}catch(e){if(invited)await admin.auth.admin.deleteUser(authUser.id).catch(()=>undefined);throw e}}
if(action==='invite_player'){const {email,username,displayName}=identity(body);const openingBalance=Math.max(0,Math.floor(Number(body.opening_balance||0)));let agentId=String(body.agent_id||'');if(operator.profile.role==='agent'){if(!operator.agent?.can_manage_users)throw new Error('FSA_MANAGE_USERS_REQUIRED');if(openingBalance>0&&!operator.agent?.can_cashier)throw new Error('FSA_CASHIER_REQUIRED');agentId=String(operator.profile.agent_id)}else if(operator.profile.role==='distributor'){if(!operator.distributor?.can_manage_users)throw new Error('FSA_MANAGE_USERS_REQUIRED');if(openingBalance>0&&!operator.distributor?.can_cashier)throw new Error('FSA_CASHIER_REQUIRED')}if(!agentId)throw new Error('FSA_AGENT_REQUIRED');const ar=await admin.from('fsa_agents').select('id,distributor_id,status').eq('id',agentId).maybeSingle();if(ar.error)throw ar.error;if(!ar.data||ar.data.status!=='active')throw new Error('FSA_AGENT_INACTIVE');if(operator.profile.role==='distributor'&&ar.data.distributor_id!==operator.profile.distributor_id)throw new Error('FSA_SCOPE_DENIED');if(operator.profile.role==='agent'&&ar.data.id!==operator.profile.agent_id)throw new Error('FSA_SCOPE_DENIED');const {authUser,invited}=await provisionAuth(email,displayName,'player',PLAYER_URL);try{const requested=Array.isArray(body.game_ids)?body.game_ids.map(String):null;const {data:playerId,error}=await admin.rpc('fsa_service_create_network_player',{p_actor_user_id:operator.user.id,p_auth_user_id:authUser.id,p_username:username,p_display_name:displayName,p_agent_id:agentId,p_opening_balance:openingBalance,p_game_ids:requested,p_notes:String(body.notes||'').slice(0,500)});if(error)throw error;const p=await admin.from('fsa_players').select('id,username,display_name,agent_id,status,balance,auth_user_id').eq('id',playerId).single();if(p.error)throw p.error;return json(req,{ok:true,invited,player:p.data})}catch(e){if(invited)await admin.auth.admin.deleteUser(authUser.id).catch(()=>undefined);throw e}}
return json(req,{error:'UNKNOWN_ACTION'},400)}catch(error){const message=error instanceof Error?error.message:'UNKNOWN_ERROR';const status=message.includes('AUTH')?401:(message.includes('MFA')||message.includes('FOUNDER')||message.includes('SCOPE')||message.includes('REQUIRED'))?403:(message.includes('INVALID')||message.includes('CEILING')||message.includes('DENIED')||message.includes('EXISTS'))?400:500;return json(req,{error:message},status)}})
